---
title: "CC Testing Past 3y"
subtitle: "Note that all of the Southern African country surveys and WHS only asked about pap smears, and all the other sub-Saharan African country surveys outside of WHS asked about CC testing in general"
output:
  pdf_document:
    fig_crop: FALSE
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,
                      warning = F,
                      message = F)
knitr::knit_hooks$set(crop = function(before, options, envir) {})
```

```{r import}
library(haven)
library(dplyr)
library(survey)
library(ggplot2)
library(readxl)
source("df_functions.R") #functions created for dataframes
load("Cleaned Indv Surveys") #from Combine Clean Surveys.Rmd
load("Cleaned Pooled Surveys") #from Combine Clean Surveys.Rmd

surveys <- read_excel("surveys.xlsx", sheet = 1)
all_q <- read_excel("surveys.xlsx", sheet = 2)
```

```{r age settings}
#set based on which age groups we want survey summary estimates from
agegr <- data.frame(c(15, 18, 15, 25, 30, 50, seq(15, 65, 5), 0), c(49, 49, 29, 49, 49, 1000, seq(19, 64, 5), 1000, 1000))
df <- data.frame(agegr = c("15-49","18-49", "15-29", "25-49", "30-49", "50-65+", 
                           "15-19", "20-24", "25-29", "30-34", "35-39", "40-44", 
                           "45-49", "50-54", "55-59", "60-64", "65-1000", "All"))
options(survey.lonely.psu="adjust")
```

# Proportion cc tested in the past 3 years
```{r function for prop tested in past 3y function}
#function for general cc testing
cctestpast3y <- function(df, age1, age2){
  sub_df <- filter(df, age >= age1 & age <= age2 & !is.na(cc_test_past_3y))
  
  if(nrow(sub_df) <= 1){ #done for age groups that have 1 or less people
    return(data.frame("Mean" = NA, "Lower" = NA, "Upper" = NA))
    
  }else{
    design <- svydesign(data = sub_df, weights = ~weight, id = ~psu, strata = ~strata, nest = T) 
    m <- svyciprop(~cc_test_past_3y, design = design)
    ci <- confint(m)
  
    return(data.frame("Mean" = as.numeric(m[1]), "Lower" = ci[1], "Upper" = ci[2]))
  }
}

#function for pap smear
papsmearpast3y <- function(df, age1, age2){
  sub_df <- filter(df, age >= age1 & age <= age2 & !is.na(pap_smear_past_3y))
  
  if(nrow(sub_df) <= 1){ #done for age groups that have 1 or less people
    return(data.frame("Mean" = NA, "Lower" = NA, "Upper" = NA))
    
  }else{
    design <- svydesign(data = sub_df, weights = ~weight, id = ~psu, strata = ~strata, nest = T) #may need to add strata
    m <- svyciprop(~pap_smear_past_3y, design = design)
    ci <- confint(m)
  
    return(data.frame("Mean" = as.numeric(m[1]), "Lower" = ci[1], "Upper" = ci[2]))
  }
}
```
```{r dhs}
#Benin
cctestpast3y_bndhs <- df_age_fig(agegr, bndhs, cctestpast3y, df)
cctestpast3y_bndhs$df <- "bndhs"

#Cameroon
cctestpast3y_cmdhs <- df_age_fig(agegr, cmdhs, cctestpast3y, df)
cctestpast3y_cmdhs$df <- "cmdhs"

#Lesotho
papsmearpast3y_ls9dhs <- df_age_fig(agegr, ls9dhs, papsmearpast3y, df)
papsmearpast3y_ls9dhs$df <- "ls9dhs"

papsmearpast3y_ls14dhs <- df_age_fig(agegr, ls14dhs, papsmearpast3y, df)
papsmearpast3y_ls14dhs$df <- "ls14dhs"

#South Africa
papsmearpast3y_sadhs <- df_age_fig(agegr, sadhs, papsmearpast3y, df)
papsmearpast3y_sadhs$df <- "sadhs"

#Zimbabwe
cctestpast3y_zwdhs <- df_age_fig(agegr, zwdhs, cctestpast3y, df)
cctestpast3y_zwdhs$df <- "zwdhs"
```
```{r phia}
cctestpast3y_phia_list <- list(NA)
cctestpast3y_phia <- data.frame(df = NA, agegr = NA)
phia_names <- c("ethphia", "mlphia", "rwphia", "tzphia", "zmphia", "zwphia")

n = 1
for(i in 1:length(phia_list)){
  df <- df_age_fig(agegr, phia_list[[i]], cctestpast3y, df)
  cctestpast3y_phia_list[[i]] <- df
  cctestpast3y_phia[c(n:(n+nrow(df)-1)), 2:5] <- df
  cctestpast3y_phia[c(n:(n+nrow(df)-1)), 1] <- phia_names[i]
  
  df_name <- paste0("cctestpast3y_", phia_names[i])
  names(cctestpast3y_phia_list)[i] <- df_name 
  
  n = n+nrow(df)
}
```
```{r sabssm}
#South Africa
papsmearpast3y_sabssm <- df_age_fig(agegr, sabssm, papsmearpast3y, df)
papsmearpast3y_sabssm$df <- "sabssm"
```
```{r sage}
#Ghana
papsmearpast3y_ghsage <- df_age_fig(agegr, ghsage, papsmearpast3y, df)
papsmearpast3y_ghsage$df <- "ghsage"

#South Africa
papsmearpast3y_sasage <- df_age_fig(agegr, sasage, papsmearpast3y, df)
papsmearpast3y_sasage$df <- "sasage"
```
```{r whs}
papsmearpast3y_whs_list <- list(NA)
papsmearpast3y_whs <- data.frame(df = NA, agegr = NA)
whs_names <- c("bfwhs", "chwhs", "ciwhs", "cmwhs", "cnwhs", "ethwhs", "ghwhs", 
               "knwhs", "mawhs", "mlwhs", "mrtwhs", "muswhs", "nmwhs", 
               "sawhs", "snwhs", "szwhs", "zmwhs", "zwwhs")

n = 1
for(i in 1:length(whs_list)){
  svy <- whs_list[[i]]
  svy <- svy[!is.na(svy$strata),] #remove the 4 strata nas from kenya and namibia
  df <- df_age_fig(agegr, svy, papsmearpast3y, df)
  papsmearpast3y_whs_list[[i]] <- df
  papsmearpast3y_whs[c(n:(n+nrow(df)-1)), 2:5] <- df
  papsmearpast3y_whs[c(n:(n+nrow(df)-1)), 1] <- whs_names[i]
  
  df_name <- paste0("papsmearpast3y_", whs_names[i])
  names(papsmearpast3y_whs_list)[i] <- df_name 
  
  n = n+nrow(df)
}

```
```{r combine}
cctestpast3y_df <- rbind(cctestpast3y_bndhs,
                         cctestpast3y_cmdhs,
                         cctestpast3y_zwdhs,
                         cctestpast3y_phia)
cctestpast3y_df$Type <- "General CC Test"

papsmearpast3y_df <- rbind(papsmearpast3y_ls9dhs,
                        papsmearpast3y_ls14dhs,
                        papsmearpast3y_sadhs,
                        papsmearpast3y_sabssm,
                        papsmearpast3y_whs)
papsmearpast3y_df$Type <- "Pap Smear"

testpast3y_df <- rbind(cctestpast3y_df,
                    papsmearpast3y_df)

testpast3y_df <- left_join(testpast3y_df, surveys)
```
```{r add new surveys}
# new_surveys <- rbind(papsmearpast3y_sasage)
# new_surveys <- left_join(new_surveys, surveys)
# new_surveys$Type <- c("Pap Smear")
# testpast3y_df <- rbind(testpast3y_df, select(new_surveys, -"microdata"))
```

```{r plots by Country}
ggplot(testpast3y_df[!is.na(testpast3y_df$Country) & testpast3y_df$agegr == "All",], aes(x = Year, y = Mean, colour = Region)) +
  geom_smooth(method = lm) +
  geom_point() +
  geom_errorbar(aes(ymin=Lower, ymax=Upper), width=.5) +
  ylim(0,1) +
  ggtitle("Raw survey statistics: Proportion tested for CC in the past 3 years among all women\n(includes dath from both general CC testing and pap smear only)") +
  theme(axis.text.x = element_text(size = 8, angle = 90, hjust=0.95, vjust=0.2), legend.position = "bottom", legend.text = element_text(size=6), legend.key.size = unit(0.5, 'cm')) +
  facet_wrap(~Country)
```
\newpage

# Proportion cc tested in the past 3 years by HIV status
```{r hiv age settings}
#set based on which age groups we want survey summary estimates from
agegr <- data.frame(c(15, 18, 15, 25, 30, 50, seq(15, 65, 5), 0), c(49, 49, 29, 49, 49, 1000, seq(19, 64, 5), 1000, 1000))
df <- data.frame(agegr = c(rep("15-49", 2),
                           rep("18-49", 2),
                           rep("15-29", 2), 
                           rep("25-49", 2), 
                           rep("30-49", 2), 
                           rep("50-65+", 2),
                           rep("15-19", 2), 
                           rep("20-24", 2), 
                           rep("25-29", 2), 
                           rep("30-34", 2), 
                           rep("35-39", 2), 
                           rep("40-44", 2), 
                           rep("45-49", 2),
                           rep("50-54", 2),
                           rep("55-59", 2),
                           rep("60-64", 2),
                           rep("65-1000", 2),
                           rep("All", 2)))

options(survey.lonely.psu="adjust")
```
```{r prop tested in past 3y by hiv function}
#function for general cc testing
hiv_cctestpast3y <- function(df, age1, age2){
  sub_df <- filter(df, age >= age1 & age <= age2 & !is.na(cc_test_past_3y) & !is.na(hivstat))
  #sub_df <- filter(df, !is.na(cc_test_past_3y) & !is.na(hivstat)) #used if no stratification by age needed
  
  if(nrow(sub_df) <= 1){ #done for age groups + hiv status that have 1 or less people
    return(data.frame("Mean" = NA, "Lower" = NA, "Upper" = NA))
    
  }else{
    design <- svydesign(data = sub_df, weights = ~weight, id = ~psu, strata = ~strata, nest = T) #may need to add strata
    m <- svyby(~cc_test_past_3y, ~hivstat, svyciprop, design = design, vartype = "ci", method = "beta")

    results <- data.frame(Status = c("HIV-", "HIV+"),
                          Mean = m[,2], Lower = m[,3], Upper = m[,4])
    return(results)
  }
}

#function for pap smear
hiv_papsmearpast3y <- function(df, age1, age2){
  sub_df <- filter(df, age >= age1 & age <= age2 & !is.na(pap_smear_past_3y) & !is.na(hivstat))
  #sub_df <- filter(df, !is.na(pap_smear_past_3y) & !is.na(hivstat))
  
  if(nrow(sub_df) <= 1){ #done for age groups + hiv status that have 1 or less people
    return(data.frame("Mean" = NA, "Lower" = NA, "Upper" = NA))
    
  }else{
    
    design <- svydesign(data = sub_df, weights = ~weight, id = ~psu, strata = ~strata, nest = T) #may need to add strata
    m <- svyby(~pap_smear_past_3y, ~hivstat, svyciprop, design = design, vartype = "ci", method = "beta")
  
    results <- data.frame(Status = c("HIV-", "HIV+"),
                          Mean = m[,2], Lower = m[,3], Upper = m[,4])
    return(results)
  }
}
```
```{r dhs hiv}
#Cameroon
hiv_cctestpast3y_cmdhs <- df_age_fig(agegr, cmdhs, hiv_cctestpast3y, df)
hiv_cctestpast3y_cmdhs$df <- "cmdhs"

#Lesotho
hiv_papsmearpast3y_ls9dhs <- df_age_fig(agegr, ls9dhs, hiv_papsmearpast3y, df)
hiv_papsmearpast3y_ls9dhs$df <- "ls9dhs"

hiv_papsmearpast3y_ls14dhs <- df_age_fig(agegr, ls14dhs, hiv_papsmearpast3y, df)
hiv_papsmearpast3y_ls14dhs$df <- "ls14dhs"

#South Africa
hiv_papsmearpast3y_sadhs <- df_age_fig(agegr, sadhs, hiv_papsmearpast3y, df)
hiv_papsmearpast3y_sadhs$df <- "sadhs"

#Zimbabwe
hiv_cctestpast3y_zwdhs <- df_age_fig(agegr, zwdhs, hiv_cctestpast3y, df)
hiv_cctestpast3y_zwdhs$df <- "zwdhs"
```
```{r phia hiv}
hiv_cctestpast3y_phia_list <- list(NA)
hiv_cctestpast3y_phia <- data.frame(df = NA, agegr = NA)
phia_names <- c("ethphia", "mlphia", "rwphia", "tzphia", "zmphia", "zwphia")

n = 1
for(i in 1:length(phia_list)){
  df <- df_age_fig(agegr, phia_list[[i]], hiv_cctestpast3y, df)
  hiv_cctestpast3y_phia_list[[i]] <- df
  hiv_cctestpast3y_phia[c(n:(n+nrow(df)-1)), 2:6] <- df
  hiv_cctestpast3y_phia[c(n:(n+nrow(df)-1)), 1] <- phia_names[i]
  
  df_name <- paste0("hiv_cctestpast3y_", phia_names[i])
  names(hiv_cctestpast3y_phia_list)[i] <- df_name 
  
  n = n+nrow(df)
}
```
```{r sabssm hiv}
#South Africa
hiv_papsmearpast3y_sabssm <- df_age_fig(agegr, sabssm, hiv_papsmearpast3y, df)
hiv_papsmearpast3y_sabssm$df <- "sabssm"
```
```{r combine hiv}
hiv_cctestpast3y_df <- rbind(hiv_cctestpast3y_cmdhs,
                             hiv_cctestpast3y_zwdhs,
                             hiv_cctestpast3y_phia)
                             #hiv_cctestpast3y_pooled)
hiv_cctestpast3y_df$Type <- "General CC Test"

hiv_papsmearpast3y_df <- rbind(hiv_papsmearpast3y_ls9dhs,
                               hiv_papsmearpast3y_ls14dhs,
                               hiv_papsmearpast3y_sadhs,
                               hiv_papsmearpast3y_sabssm)
                               #hiv_papsmearpast3y_pooled)
hiv_papsmearpast3y_df$Type <- "Pap Smear"

hiv_testpast3y_df <- rbind(hiv_cctestpast3y_df,
                           hiv_papsmearpast3y_df)

hiv_testpast3y_df <- left_join(hiv_testpast3y_df, surveys)
```

```{r plots hiv by Country}
a <- filter(hiv_testpast3y_df, agegr == "15-19" |
                             agegr == "20-24"| 
                             agegr == "25-29"|
                             agegr == "30-34"| 
                             agegr == "35-39"| 
                             agegr == "40-44"| 
                             agegr == "45-49"| 
                             agegr == "50-54"| 
                             agegr == "55-59"| 
                             agegr == "60-64"| 
                             agegr == "65-1000")
a$agegr <- factor(a$agegr, levels = c("15-19", "20-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50-54", "55-59", "60-64", "65-1000"))
ggplot(a, aes(x=agegr, y = Mean, colour = Status, fill = Status)) +
  geom_bar(position = "dodge", stat = "identity") +
  facet_wrap(~df)
```

```{r save datasets}
#load("CC Testing Past 3Y")
save(testpast3y_df,
     # hiv_testpast3y_1849_df,
     # hiv_testpast3y_3049_df,
     # hiv_testpast3y_1549_df,
     hiv_testpast3y_df,
     file = "CC Testing Past 3Y")
```