---
title: "SAGE"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import}
library(haven)
library(dplyr)
library(survey)
library(ggplot2)
source("df_functions.R")

ghsage_raw <- read_dta("~/Documents/GitHub/HPV-HIV-Model/SAGE/Ghana/GhanaINDData.dta")
sasage_raw <- read_dta("~/Documents/GitHub/HPV-HIV-Model/SAGE/South Africa/SouthAfricaINDData.dta")
```

#Clean data
```{r ghana}
ghsage <- select(ghsage_raw,
                 psu = q0101b,
                 strata,
                 weight = pweight,
                 age = q0407,
                 sex = q0406, # 1=male; 2=female
                 urban_rural = q0104, # 1=urban; 2=rural; 8/9 = DK/NA
                 edu = q0409,
                 marital_status = q1012, 
                 #cervical cancer questions
                 last_pelvic_exam = q4078,
                 last_pelvic_exam_pap = q4079)
#table(ghsage_raw[ghsage_raw$q0406 == 2,]$q0407)
ghsage$Country <- "Ghana"
ghsage$Year <- "2007"
ghsage$df <- "ghsage"

#recode education
ghsage$edu[ghsage$edu == 0] <- 0 #no schooling
ghsage$edu[ghsage$edu == 1 | ghsage$edu == 2] <- 1 #primary education
ghsage$edu[ghsage$edu == 3 | ghsage$edu == 4] <- 2 #secondary education
ghsage$edu[ghsage$edu == 5 | ghsage$edu == 6] <- 3 #more than secondary schooling
ghsage$edu[ghsage$edu == 8] <- NA #don't know
  
#recode marital_status
ghsage$marital_status[ghsage$marital_status == 1] <- 0 #never in union
ghsage$marital_status[ghsage$marital_status == 2] <- 1 #married
ghsage$marital_status[ghsage$marital_status == 3] <- 2 #cohabiting
ghsage$marital_status[ghsage$marital_status == 4] <- 4 #separated/divorced
ghsage$marital_status[ghsage$marital_status == 5] <- 3 #widowed
ghsage$marital_status[ghsage$marital_status == 8] <- NA #don't know
ghsage$marital_status[ghsage$marital_status == 9] <- NA #NA

##cervical cancer questions
#the problem with these questions is that it misses people who didn't have a pap smear at their last pelvic exam but had one in their second to last or third to last
ghsage$last_pelvic_exam[ghsage$last_pelvic_exam == -8] <- NA #don't know
ghsage$last_pelvic_exam_pap[ghsage$last_pelvic_exam_pap == 8] <- NA #don't know
ghsage$last_pelvic_exam_pap[ghsage$last_pelvic_exam_pap == 9] <- NA #not applicable
ghsage$last_pelvic_exam_pap[is.na(ghsage$last_pelvic_exam)] <- NA #not applicable if didn't answer first question
ghsage$last_pelvic_exam[ghsage$last_pelvic_exam != 98 & is.na(ghsage$last_pelvic_exam_pap)] <- NA #not applicable if didn't answer second question when you're supposed to

ghsage$pap_smear_past_1y[ghsage$last_pelvic_exam_pap == 1 & ghsage$last_pelvic_exam <= 1] <- 1
ghsage$pap_smear_past_1y[ghsage$last_pelvic_exam_pap == 2] <- 0 #this assumes that those who said no to a pap smear in their LAST pelvic exam did not have another pelvic exam within the last year that was a pap smear
ghsage$pap_smear_past_1y[ghsage$last_pelvic_exam > 1] <- 0 #this would include people who responded saying they've never had a pelvic exam

ghsage$pap_smear_past_3y[ghsage$last_pelvic_exam_pap == 1 & ghsage$last_pelvic_exam <= 3] <- 1
ghsage$pap_smear_past_3y[ghsage$last_pelvic_exam_pap == 2] <- 0 #this assumes that those who said no to a pap smear in their LAST pelvic exam did not have another pelvic exam within the past 3 years that was a pap smear
ghsage$pap_smear_past_3y[ghsage$last_pelvic_exam > 3] <- 0 #this would include people who responded saying they've never had a pelvic exam

ghsage$ever_had_pap_smear <- NA
ghsage$ever_had_pap_smear[ghsage$last_pelvic_exam_pap == 1 & ghsage$last_pelvic_exam <= 9] <- 1
ghsage$ever_had_pap_smear[ghsage$last_pelvic_exam_pap == 2] <- 0 #this assumes that those who said no to a pap smear in their LAST pelvic exam did not have another pelvic exam within the past 3 years that was a pap smear
ghsage$ever_had_pap_smear[ghsage$last_pelvic_exam > 9] <- 0 #this would include people who responded saying they've never had a pelvic exam - i also checked and no ones age is 

sum(table(ghsage$ever_had_pap_smear))
sum(table(ghsage$pap_smear_past_1y))

ghsage <- filter(ghsage, sex == 2 & !is.na(weight))
sum(table(ghsage$pap_smear_past_3y))
sum(table(ghsage_raw[ghsage_raw$q0406 == 2 & ghsage_raw$q0407 >= 15 & ghsage_raw$q0407 <= 19,]$q4078))
sum(table(ghsage_raw[ghsage_raw$q0406 == 2,]$q4078))
table(ghsage_raw$q4078)
table(ghsage_raw$q4079)

#View(ghsage_raw[,c("q4078", "q4079")])
sum(table(ghsage$ever_had_pap_smear))
sum(table(ghsage$pap_smear_past_1y))
table(ghsage$last_pelvic_exam_pap)
sum(table(ghsage$last_pelvic_exam))
```
```{r south africa}
sasage <- select(sasage_raw,
                 psu = q0101b,
                 strata,
                 weight = pweight,
                 age = q0407,
                 sex = q0406, # 1=male; 2=female
                 urban_rural = q0104, # 1=urban; 2=rural; 8/9 = DK/NA
                 edu = q0409,
                 marital_status = q1012, 
                 #cervical cancer questions
                 last_pelvic_exam = q4078,
                 last_pelvic_exam_pap = q4079)
#table(sasage_raw[sasage_raw$q0406 == 2,]$q0407)
sasage$Country <- "South Africa"
sasage$Year <- "2007"
sasage$df <- "sasage"

#recode education
sasage$edu[sasage$edu == 0] <- 0 #no schooling
sasage$edu[sasage$edu == 1 | sasage$edu == 2] <- 1 #primary education
sasage$edu[sasage$edu == 3 | sasage$edu == 4] <- 2 #secondary education
sasage$edu[sasage$edu == 5 | sasage$edu == 6] <- 3 #more than secondary schooling
sasage$edu[sasage$edu == 8] <- NA #don't know
  
#recode marital_status
sasage$marital_status[sasage$marital_status == 1] <- 0 #never in union
sasage$marital_status[sasage$marital_status == 2] <- 1 #married
sasage$marital_status[sasage$marital_status == 3] <- 2 #cohabiting
sasage$marital_status[sasage$marital_status == 4] <- 4 #separated/divorced
sasage$marital_status[sasage$marital_status == 5] <- 3 #widowed
sasage$marital_status[sasage$marital_status == 8] <- NA #don't know
sasage$marital_status[sasage$marital_status == 9] <- NA #NA

##cervical cancer questions
#the problem with these questions is that it misses people who didn't have a pap smear at their last pelvic exam but had one in their second to last or third to last
sasage$last_pelvic_exam[sasage$last_pelvic_exam == -8] <- NA #don't know
sasage$last_pelvic_exam_pap[sasage$last_pelvic_exam_pap == 0] <- NA #don't know
sasage$last_pelvic_exam_pap[sasage$last_pelvic_exam_pap == 8] <- NA #don't know
sasage$last_pelvic_exam_pap[sasage$last_pelvic_exam_pap == 9] <- NA #not applicable
sasage$last_pelvic_exam_pap[is.na(sasage$last_pelvic_exam)] <- NA #not applicable if didn't answer first question
sasage$last_pelvic_exam[sasage$last_pelvic_exam != 98 & is.na(sasage$last_pelvic_exam_pap)] <- NA #not applicable if didn't answer second question when you're supposed to

sasage$pap_smear_past_1y[sasage$last_pelvic_exam_pap == 1 & sasage$last_pelvic_exam <= 1] <- 1
sasage$pap_smear_past_1y[sasage$last_pelvic_exam_pap == 2] <- 0 #this assumes that those who said no to a pap smear in their LAST pelvic exam did not have another pelvic exam within the last year that was a pap smear
sasage$pap_smear_past_1y[sasage$last_pelvic_exam > 1] <- 0 #this would include people who responded saying they've never had a pelvic exam

sasage$pap_smear_past_3y[sasage$last_pelvic_exam_pap == 1 & sasage$last_pelvic_exam <= 3] <- 1
sasage$pap_smear_past_3y[sasage$last_pelvic_exam_pap == 2] <- 0 #this assumes that those who said no to a pap smear in their LAST pelvic exam did not have another pelvic exam within the past 3 years that was a pap smear
sasage$pap_smear_past_3y[sasage$last_pelvic_exam > 3] <- 0 #this would include people who responded saying they've never had a pelvic exam

sasage$ever_had_pap_smear[sasage$last_pelvic_exam_pap == 1] <- 1
sasage$ever_had_pap_smear[sasage$last_pelvic_exam_pap == 2] <- 0 #this assumes that those who said no to a pap smear in their LAST pelvic exam did not have another pelvic exam within the past 3 years that was a pap smear
sasage$ever_had_pap_smear[sasage$last_pelvic_exam == 98] <- 0 #this would include people who responded saying they've never had a pelvic exam - i also checked and no ones age is 

sasage <- filter(sasage, sex == 2 & !is.na(weight))
sum(table(sasage$pap_smear_past_3y))
sum(table(sasage_raw[sasage_raw$q0406 == 2 & sasage_raw$q0407 >= 15 & sasage_raw$q0407 <= 19,]$q4078))
sum(table(sasage_raw[sasage_raw$q0406 == 2,]$q4078))
table(sasage_raw$q4078)
table(sasage_raw$q4079)

#View(sasage_raw[,c("q4078", "q4079")])
sum(table(sasage$ever_had_pap_smear))
sum(table(sasage$pap_smear_past_1y))
table(sasage$last_pelvic_exam_pap)
table(sasage$last_pelvic_exam)
```
```{r missing data}
ghsage_raw <- read_dta("~/Documents/GitHub/HPV-HIV-Model/SAGE/Ghana/GhanaINDData.dta")
ghsage_raw <- select(ghsage_raw,
                 age = q0407,
                 sex = q0406, # 1=male; 2=female
                 #cervical cancer questions
                 last_pelvic_exam = q4078,
                 last_pelvic_exam_pap = q4079)

age.groups = data.frame(l_age = seq(15, 65, 5), u_age = c(seq(19, 64, 5), 1000))
A <- nrow(age.groups)
for(n in 1:nrow(ghsage_raw)){
  for(a in 1:A){
    if(!is.na(ghsage_raw$age[n]) & age.groups$l_age[a] <= ghsage_raw$age[n] & age.groups$u_age[a] >= ghsage_raw$age[n]){
      agegr <- paste0(age.groups$l_age[a], "-", age.groups$u_age[a])
      ghsage_raw$agegr[n] <- agegr
    }
  }
}

dat_missing <- data.frame(Survey = NA,
                 agegr = NA,
                 elg_resp = NA,
                 resp = NA,
                 dk = NA,
                 missing = NA)
n=1
for(a in 1:sort(length(unique(ghsage_raw$agegr)))){
   gr <- sort(unique(ghsage_raw$agegr))[a]
    df <- filter(ghsage_raw, agegr == gr & sex == 2)
    id <- "ghsage"
    tbl <- table(df$last_pelvic_exam) #everyone who responded to last_pelvic_exam_pap responded to last_pelvic_exam
    df_tbl <- data.frame(tbl)
    
    elg_resp <- nrow(df)
    resp <- sum(tbl)
    missing <- elg_resp - resp
    dk <- df_tbl[df_tbl$Var1 == -8,]$Freq
    if(length(dk) <= 0){
      dk <- 0
    }
    print(id); print(tbl)
    dat_missing[n, ] <- c(id, gr, elg_resp, resp, dk, missing)
    n=n+1
}

sum(as.numeric(dat_missing$missing))
table(ghsage_raw$last_pelvic_exam)
```

```{r save}
save(ghsage, sasage,
     file = "Cleaned SAGE")
#load("Cleaned SAGE")
```
