---
title: "WHS"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load("Cleaned WHS")
```

```{r import + clean data}
library(haven)
library(dplyr)
library(survey)
library(ggplot2)
library(reldist)
source("df_functions.R")

read_whs <- function(iso3, full_name){
  abrvid <- read_dta(paste0("~/Documents/GitHub/HPV-HIV-Model/WHS/", iso3, "/", full_name, "-ID.dta"))
  abrv2 <- read_dta(paste0("~/Documents/GitHub/HPV-HIV-Model/WHS/", iso3, "/WHS-", full_name, "_F2.dta"))
  #abrv4 <- read_dta(paste0("~/Documents/GitHub/HPV-HIV-Model/WHS/", iso3, "/WHS-", full_name, "_F4.dta"))
  abrv5 <- read_dta(paste0("~/Documents/GitHub/HPV-HIV-Model/WHS/", iso3, "/WHS-", full_name, "_F5.dta"))
  
  abrv <- left_join(abrvid, abrv2)
  #abrv <- left_join(abrv, abrv4)
  abrv <- left_join(abrv, abrv5)
  
  abrvwhs <- select(abrv,
                    c(psu = PSU,
                      strata, 
                      weight = pweight,
                      age = q1002,
                      sex = q1001,
                      #cervical cancer questions
                      last_pelvic_exam = q6300,
                      last_pelvic_exam_pap = q6301))
  
  #Recode
  
  ##determinants
  abrvwhs$sex[abrvwhs$sex == 2] <- 0 #men == 0 for now
  abrvwhs$sex[abrvwhs$sex == 1] <- 2 #code females as 2 to match the other surveys
  abrvwhs$sex[abrvwhs$sex == 0] <- 1 #code males to 1

  #create age groups variable
  age.groups = data.frame(l_age = seq(15, 65, 5), u_age = c(seq(19, 64, 5), 1000))
  A <- nrow(age.groups)
  abrvwhs$age.group = NA
  for(n in 1:nrow(abrvwhs)){
    for(a in 1:A){
      if(age.groups$l_age[a] <= abrvwhs$age[n] & age.groups$u_age[a] >= abrvwhs$age[n] & !is.na(abrvwhs$age[n])){
      abrvwhs$age.group[n] <- a
      }
    }
  }
  abrvwhs$age.group <- factor(abrvwhs$age.group, labels = c("15-19", "20-24", "25-29", "30-34",
                                                            "35-39", "40-44", "45-49", "50-54", 
                                                            "55-59", "60-64", "65+"))
  
  abrvwhs$Year <- 2003
  
  abrvwhs <- filter(abrvwhs, sex == 2 & !is.na(weight))
  
  ##cervical cancer questions
  #changing no from 5 to 0
  abrvwhs$last_pelvic_exam_pap[abrvwhs$last_pelvic_exam_pap == 5] <- 0
  abrvwhs$last_pelvic_exam_pap[abrvwhs$last_pelvic_exam != 1] <- NA #remove values for this question if did not report pelvic exam in the past 3 years
  abrvwhs$last_pelvic_exam_pap[is.na(abrvwhs$last_pelvic_exam)] <- NA #remove values for this question if preceding question (ever had pelvic exam) was NA 

  #creating a new variable for pap smear in the past 3 years among everyone
  abrvwhs$pap_smear_past_3y <- NA
  abrvwhs$pap_smear_past_3y[!is.na(abrvwhs$last_pelvic_exam)] <- 0 #keeps the denominator to among all women who answered the pelvic exam question
  for(i in 1:nrow(abrvwhs)){ #adds values from those who answered if they had a pap smear
    if(!is.na(abrvwhs$last_pelvic_exam_pap[i])){
      abrvwhs$pap_smear_past_3y[i] <- abrvwhs$last_pelvic_exam_pap[i] #this assumes that those who said no to a pap smear in their LAST pelvic exam did not have another pelvic exam within the past 3 years that was a pap smear
    }
  }
  
  return(abrvwhs)
}

bfwhs <- read_whs("BFA", "Burkina")
chwhs <- read_whs("TCD", "Chad")
ciwhs <- read_whs("CIV", "CotedIvoire")
cmwhs <- read_whs("COM", "Comoros")
cnwhs <- read_whs("COG", "Congo")
ethwhs <- read_whs("ETH", "Ethiopia")
ghwhs <- read_whs("GHA", "Ghana")
knwhs <- read_whs("KEN", "Kenya")
mawhs <- read_whs("MLI", "Mali")
mlwhs <- read_whs("MWI", "Malawi")
mrtwhs <- read_whs("MRT", "Mauritania")
muswhs <- read_whs("MUS", "Mauritius")
nmwhs <- read_whs("NAM", "Namibia")
sawhs <- read_whs("ZAF", "SouthAfrica")
snwhs <- read_whs("SEN", "Senegal")
szwhs <- read_whs("SWZ", "Eswatini")
zmwhs <- read_whs("ZMB", "Zambia")
zwwhs <- read_whs("ZWE", "Zimbabwe")

abrv = c("bf", "ch", "ci", "cm", "cn", "eth", 
         "gh", "kn", "ma", "ml", "mrt", "mus", 
         "nm", "sa", "sn", "sz", "zm", "zw")

countries = c("Burkina Faso", "Chad", "Cote d'Ivoire", "Comoros", "Congo (Rep)", "Ethiopia", "Ghana", "Kenya", "Mali", "Malawi", "Mauritania", "Mauritius", "Namibia", "South Africa", "Senegal", "Eswatini", "Zambia", "Zimbabwe")

whs <- list(bfwhs, chwhs, ciwhs, cmwhs, cnwhs, ethwhs, ghwhs, 
               knwhs, mawhs, mlwhs, mrtwhs, muswhs, nmwhs, 
               sawhs, snwhs, szwhs, zmwhs, zwwhs)

whs_names <- c("bfwhs", "chwhs", "ciwhs", "cmwhs", "cnwhs", "ethwhs", "ghwhs", 
               "knwhs", "mawhs", "mlwhs", "mrtwhs", "muswhs", "nmwhs", 
               "sawhs", "snwhs", "szwhs", "zmwhs", "zwwhs")

names(whs) <- countries

#adding country and df variable
for(i in 1:length(whs)){
  whs[[i]]$Country <- countries[i]
  whs[[i]]$df <- paste0(abrv[i], "whs")
  #print(nrow(whs_list[[i]]))
}

##
df <- data.frame(names = whs_names,
                 total_women = NA,
                 total_women_answered = NA,
                 num_had_pap = NA)
for(i in 1:length(whs)){
  df[i,2] <- sum(table(whs[[i]]$sex))
  df[i,3] <- sum(table(whs[[i]]$pap_smear_past_3y)) 
  df[i,4] <- table(whs[[i]]$pap_smear_past_3y)[2]
}
```
```{r missing data}
df <- data.frame(iso3 = c("BFA", "TCD", "CIV", "COM", "COG", "ETH", "GHA", "KEN", "MLI", 
                          "MWI", "MRT", "MUS", "NAM", "ZAF", "SEN", "SWZ", "ZMB", "ZWE"),
                 full_name = c("Burkina", "Chad", "CotedIvoire", "Comoros", "Congo", "Ethiopia", "Ghana", "Kenya", "Mali", 
                               "Malawi", "Mauritania", "Mauritius", "Namibia", "SouthAfrica", "Senegal", "Eswatini", "Zambia", "Zimbabwe"))
whs_names <- c("bfwhs", "chwhs", "ciwhs", "cmwhs", "cnwhs", "ethwhs", "ghwhs", 
               "knwhs", "mawhs", "mlwhs", "mrtwhs", "muswhs", "nmwhs", 
               "sawhs", "snwhs", "szwhs", "zmwhs", "zwwhs")
whs_list <- list(NA)
for(w in 1:nrow(df)){
  abrv5 <- read_dta(paste0("~/Documents/GitHub/HPV-HIV-Model/WHS/", df[w,1], "/WHS-", df[w,2], "_F5.dta"))
  abrvwhs <- select(abrv5,
                 sex = q1001, #male = 2; female = 1
                 age = q1002,
                 last_pelvic_exam = q6300,
                 last_pelvic_exam_pap = q6301)
  abrvwhs$last_pelvic_exam_pap[abrvwhs$last_pelvic_exam_pap == 5] <- 0
  abrvwhs$last_pelvic_exam_pap[abrvwhs$last_pelvic_exam != 1] <- NA #remove values for this question if did not report pelvic exam in the past 3 years
  abrvwhs$last_pelvic_exam_pap[is.na(abrvwhs$last_pelvic_exam)] <- NA #remove values for this question if preceding question (ever had pelvic exam) was NA 

  #creating a new variable for pap smear in the past 3 years among everyone
  abrvwhs$pap_smear_past_3y <- NA
  abrvwhs$pap_smear_past_3y[!is.na(abrvwhs$last_pelvic_exam)] <- 0 #keeps the denominator to among all women who answered the pelvic exam question
  for(i in 1:nrow(abrvwhs)){ #adds values from those who answered if they had a pap smear
    if(!is.na(abrvwhs$last_pelvic_exam_pap[i])){
      abrvwhs$pap_smear_past_3y[i] <- abrvwhs$last_pelvic_exam_pap[i]
    }
  }
  age.groups = data.frame(l_age = seq(15, 70, 5), u_age = c(seq(19, 69, 5), 1000))
  A <- nrow(age.groups)
  for(n in 1:nrow(abrvwhs)){
    for(a in 1:A){
      if(!is.na(abrvwhs$age[n]) & age.groups$l_age[a] <= abrvwhs$age[n] & age.groups$u_age[a] >= abrvwhs$age[n]){
        agegr <- paste0(age.groups$l_age[a], "-", age.groups$u_age[a])
        abrvwhs$agegr[n] <- agegr
      }
    }
  }
  abrvwhs$df <- whs_names[w]
  whs_list[[w]] <- abrvwhs
}

names(whs_list) <- whs_names

dat_missing <- data.frame(Survey = NA,
                 agegr = NA,
                 elg_resp = NA,
                 resp = NA,
                 dk = NA,
                 missing = NA)

n=1
for(i in 1:length(whs_list)){
  for(a in 1:length(sort(unique(whs_list[[i]]$agegr)))){
    gr <- sort(unique(whs_list[[i]]$agegr))[a]
    df <- filter(whs_list[[i]], agegr == gr & sex == 1)
    id <- names(whs_list)[i]
    tbl <- table(df$pap_smear_past_3y)
    df_tbl <- data.frame(tbl)
    
    elg_resp <- nrow(df)
    resp <- sum(tbl)
    missing <- elg_resp - resp
    
    print(id); print(tbl)
    dat_missing[n, ] <- c(id, gr, elg_resp, resp, dk, missing)
    n=n+1
  }
}

```

```{r plot}
ggplot(papsmearpast3y_whs, aes(x = Age.Groups, y = Mean, fill = Country)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(aes(ymin=Lower, ymax=Upper), width=.5, position = position_dodge(0.9)) +
  ylim(0,1) +
  facet_wrap(~Country, nrow = 6) +
  theme(axis.text.x = element_text(size = 8, angle = 90, hjust=0.95, vjust=0.2)) +
  ggtitle("WHS: Proportion had a pap smear in the past 3 years among all women")
```

```{r save}
save(bfwhs, bfwhs, chwhs, ciwhs, cmwhs, cnwhs, ethwhs, ghwhs, 
     knwhs, mawhs, mlwhs, mrtwhs, muswhs, nmwhs, sawhs, snwhs, szwhs, zmwhs, zwwhs, 
     file = "New Cleaned WHS")
```