---
title: "STEPS"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import}
library(dplyr)
library(survey)
library(ggplot2)
library(haven)
library(readxl)
source("df_functions.R")

bnsteps_raw <- read.csv("~/Documents/GitHub/HPV-HIV-Model/Steps/Benin/ben2015.csv")
btsteps_raw <- read.csv("~/Documents/GitHub/HPV-HIV-Model/Steps/Botswana/bwa2014.csv")
cpvsteps_raw <- read_excel("~/Documents/GitHub/HPV-HIV-Model/Steps/Cape Verde/cpv2019.xlsx", sheet = 1)
ethsteps_raw <- read.csv("~/Documents/GitHub/HPV-HIV-Model/Steps/Ethiopia/eth2015.csv")
knsteps_raw <- read_sav("~/Documents/GitHub/HPV-HIV-Model/Steps/Kenya/ken2015.sav")
mlsteps_raw <- read.csv("~/Documents/GitHub/HPV-HIV-Model/Steps/Malawi/mwi2017.csv")
snsteps_raw <- read_sav("~/Documents/GitHub/HPV-HIV-Model/Steps/Senegal/sen2014.sav")
stpsteps_raw <- read_excel("~/Documents/GitHub/HPV-HIV-Model/Steps/Sao Tome and Principe/stp2019.xlsx", sheet = 1)
szsteps_raw <- read.csv("~/Documents/GitHub/HPV-HIV-Model/Steps/Swaziland/swz2014.csv")
ugsteps_raw <- read.csv("~/Documents/GitHub/HPV-HIV-Model/Steps/Uganda/uga2014.csv")
zmsteps_raw <- read.csv("~/Documents/GitHub/HPV-HIV-Model/Steps/Zambia/zmb2017.csv")
```

```{r benin clean}
bnsteps <- select(bnsteps_raw,
                   c(psu,
                     urban_rural = stratum, #urban = 1; rural = 2
                     weight = wstep1,
                     age,
                     sex, #Men; Women
                     #region = province, can't find the code for this
                     c10a,
                     c10b,
                     c10c,
                     income = c11,
                     edu = c5,
                     marital_status = c7,
                     ever_cc_tested = cx1))
bnsteps$ever_cc_tested[bnsteps$ever_cc_tested == 77] <- NA #code don't know as NA
bnsteps$ever_cc_tested[bnsteps$ever_cc_tested == 2] <- 0
bnsteps$Year <- 2015
bnsteps$Country <- "Benin"
bnsteps$df <- "bnsteps"

#Recode sex
bnsteps$sex[bnsteps$sex == "Men"] <- 1
bnsteps$sex[bnsteps$sex == "Women"] <- 2

#recode education
bnsteps$edu[bnsteps$edu == 1 | bnsteps$edu == 2] <- 0 #no schooling completed
bnsteps$edu[bnsteps$edu == 3] <- 1 #primary education completed
bnsteps$edu[bnsteps$edu == 4 ] <- 2 #secondary education completed
bnsteps$edu[bnsteps$edu == 5 | bnsteps$edu == 6 | bnsteps$edu == 7] <- 3 #more than secondary  schooling completed
bnsteps$edu[bnsteps$edu == 88] <- NA 

#recode marital_status
bnsteps$marital_status[bnsteps$marital_status == 1] <- 0 #never married
bnsteps$marital_status[bnsteps$marital_status == 2] <- 1 #currently married
bnsteps$marital_status[bnsteps$marital_status == 3] <- 4 #separated or divorced
bnsteps$marital_status[bnsteps$marital_status == 5] <- 3 #widowed
bnsteps$marital_status[bnsteps$marital_status == 6] <- 2 #cohabiting
bnsteps$marital_status[bnsteps$marital_status == 88] <- NA 

bnsteps <- filter(bnsteps, sex == 2 & !is.na(weight))
```
```{r botswana clean}
btsteps <- select(btsteps_raw,
                   c(psu,
                     urban_rural = stratum, #just 1 --> 1; not sure if this should be considered urban or rural however**
                     weight = wstep1,
                     age,
                     sex,
                     #region = province, can't find the code for this
                     c10a, c10b, c10c, #level of income by week, month, year
                     income = c11,
                     edu = c5,
                     marital_status = c7,
                     ever_cc_tested = cx1))
btsteps$ever_cc_tested[btsteps$ever_cc_tested == 77] <- NA #code don't know as NA
btsteps$ever_cc_tested[btsteps$ever_cc_tested == 2] <- 0
btsteps$Year <- 2014
btsteps$Country <- "Botswana"
btsteps$df <- "btsteps"

#Recode sex
btsteps$sex[btsteps$sex == "Men"] <- 1
btsteps$sex[btsteps$sex == "Women"] <- 2

#create annual income variable
btsteps$annual_income <- NA
for(i in 1:nrow(btsteps)){
  if(!is.na(btsteps$c10a[i])){
    btsteps$annual_income[i] <- btsteps$c10a[i]*52
  }else if(!is.na(btsteps$c10b[i])){
    btsteps$annual_income[i] <- btsteps$c10b[i]*12
  }else if(!is.na(btsteps$c10c[i])){
    btsteps$annual_income[i] <- btsteps$c10c[i]
  }
}

#recode education
btsteps$edu[btsteps$edu == 1 | btsteps$edu == 2] <- 0 #no schooling completed
btsteps$edu[btsteps$edu == 3] <- 1 #primary education completed
btsteps$edu[btsteps$edu == 4 | btsteps$edu == 5 | btsteps$edu == 6] <- 2 #secondary education completed
btsteps$edu[btsteps$edu == 7 | btsteps$edu == 8 | btsteps$edu == 9] <- 3 #more than secondary completed schooling
btsteps$edu[btsteps$edu == 88] <- NA 

#recode marital_status
btsteps$marital_status[btsteps$marital_status == 1] <- 0
btsteps$marital_status[btsteps$marital_status == 2] <- 1
btsteps$marital_status[btsteps$marital_status == 3] <- 4 
btsteps$marital_status[btsteps$marital_status == 5] <- 3
btsteps$marital_status[btsteps$marital_status == 6] <- 2
btsteps$marital_status[btsteps$marital_status == 88] <- NA 

btsteps <- filter(btsteps, sex == 2 & !is.na(weight))
```
```{r cape verde clean}
cpvsteps <- select(cpvsteps_raw,
                   c(psu,
                     strata = stratum,
                     weight = wstep1,
                     age,
                     sex,
                     ever_cc_tested = cx1,
                     age_first_tested = cx2,
                     last_cc_test = cx3,
                     cc_treated = cx8))

cpvsteps$Year <- 2019
cpvsteps$Country <- "Cape Verde"
cpvsteps$df <- "cpvsteps"

#Recode sex
cpvsteps$sex[cpvsteps$sex == "Men"] <- 1
cpvsteps$sex[cpvsteps$sex == "Women"] <- 2

#cervical cancer questions
cpvsteps$ever_cc_tested[cpvsteps$ever_cc_tested == 77] <- NA #code don't know as NA
cpvsteps$ever_cc_tested[cpvsteps$ever_cc_tested == 2] <- 0

cpvsteps$age_first_tested[cpvsteps$age_first_tested == 77] <- NA #code don't know as NA
cpvsteps$age_first_tested[cpvsteps$age_first_tested > cpvsteps$age] <- NA

cpvsteps$last_cc_test[cpvsteps$last_cc_test == 77] <- NA #code don't know as NA
cpvsteps$cc_test_past_1y[cpvsteps$last_cc_test == 1 & cpvsteps$ever_cc_tested == 1] <- 1
cpvsteps$cc_test_past_1y[cpvsteps$last_cc_test > 1] <- 0
cpvsteps$cc_test_past_1y[cpvsteps$ever_cc_tested == 0] <- 0

cpvsteps$cc_treated[cpvsteps$cc_treated == 77] <- NA
cpvsteps$cc_treated[cpvsteps$cc_treated == 2] <- 0

cpvsteps <- filter(cpvsteps, sex == 2 & !is.na(weight))

# sum(table(cpvsteps_raw[cpvsteps_raw$sex == "Women",]$cx1)) - 88
# sum(table(cpvsteps$ever_cc_tested))
# table(is.na(cpvsteps$ever_cc_tested))
```
```{r eswatini clean}
szsteps <- select(szsteps_raw,
                   c(psu,
                     strata = stratum,
                     #can't find urban/rural
                     weight = wstep1,
                     age,
                     sex,
                     #region = province, can't find the code for this
                     c10a,
                     c10b,
                     c10c,
                     income = c11,
                     edu = c5,
                     marital_status = c7,
                     ever_cc_tested = cx1))
szsteps$ever_cc_tested[szsteps$ever_cc_tested == 77] <- NA #code don't know as NA
szsteps$ever_cc_tested[szsteps$ever_cc_tested == 2] <- 0
szsteps$Year <- 2014
szsteps$Country <- "Eswatini"
szsteps$df <- "szsteps"

#Recode sex
szsteps$sex[szsteps$sex == "Men"] <- 1
szsteps$sex[szsteps$sex == "Women"] <- 2

#create annual income variable
szsteps$annual_income <- NA
for(i in 1:nrow(szsteps)){
  if(!is.na(szsteps$c10a[i])){
    szsteps$annual_income[i] <- szsteps$c10a[i]*52
  }else if(!is.na(szsteps$c10b[i])){
    szsteps$annual_income[i] <- szsteps$c10b[i]*12
  }else if(!is.na(szsteps$c10c[i])){
    szsteps$annual_income[i] <- szsteps$c10c[i]
  }
}

#recode education
szsteps$edu[szsteps$edu == 1 | szsteps$edu == 2] <- 0 #no schooling completed
szsteps$edu[ szsteps$edu == 3] <- 1 #primary education completed
szsteps$edu[szsteps$edu == 4 | szsteps$edu == 5] <- 2 #secondary education completed
szsteps$edu[szsteps$edu == 6 | szsteps$edu == 7] <- 3 #more than secondary schooling completed
szsteps$edu[szsteps$edu == 88] <- NA 

#recode marital_status
szsteps$marital_status[szsteps$marital_status == 1] <- 0 #never married
szsteps$marital_status[szsteps$marital_status == 2] <- 1 #currently married
szsteps$marital_status[szsteps$marital_status == 3] <- 4 #separated or divorced
szsteps$marital_status[szsteps$marital_status == 5] <- 3 #widowed
szsteps$marital_status[szsteps$marital_status == 6] <- 2 #cohabiting
szsteps$marital_status[szsteps$marital_status == 88] <- NA 

szsteps <- filter(szsteps, sex == 2 & !is.na(weight))
```
```{r ethiopia clean}
ethsteps <- select(ethsteps_raw,
                   c(psu,
                     strata = stratum,
                     weight = wstep1,
                     urban_rural = urbanrural, #urban = 1 and rural = 2
                     age = c3,
                     sex = c1,
                     region,
                     c10a,
                     c10b,
                     c10c,
                     income = c11,
                     edu = c5,
                     marital_status = c7,
                     ever_cc_tested = cx1))
ethsteps$ever_cc_tested[ethsteps$ever_cc_tested == 77] <- NA #code don't know as NA
ethsteps$ever_cc_tested[ethsteps$ever_cc_tested == 2] <- 0
ethsteps$Year <- 2015
ethsteps$Country <- "Ethiopia"
ethsteps$df <- "ethsteps"

#create annual income variable
ethsteps$annual_income <- NA
for(i in 1:nrow(ethsteps)){
  if(!is.na(ethsteps$c10a[i])){
    ethsteps$annual_income[i] <- ethsteps$c10a[i]*52
  }else if(!is.na(ethsteps$c10b[i])){
    ethsteps$annual_income[i] <- ethsteps$c10b[i]*12
  }else if(!is.na(ethsteps$c10c[i])){
    ethsteps$annual_income[i] <- ethsteps$c10c[i]
  }
}

#recode education
ethsteps$edu[ethsteps$edu == 1 | ethsteps$edu == 2 ] <- 0 #no schooling completed 
ethsteps$edu[ethsteps$edu == 3] <- 1 #primary education completed
ethsteps$edu[ethsteps$edu == 4 ] <- 2 #secondary education completed
ethsteps$edu[ethsteps$edu == 6 | ethsteps$edu == 7] <- 3 #more than secondary schooling completed
ethsteps$edu[ethsteps$edu == 88] <- NA 

#recode marital_status
ethsteps$marital_status[ethsteps$marital_status == 1] <- 0 #never married
ethsteps$marital_status[ethsteps$marital_status == 2] <- 1 #currently married
ethsteps$marital_status[ethsteps$marital_status == 3] <- 4 #separated or divorced
ethsteps$marital_status[ethsteps$marital_status == 5] <- 3 #widowed
ethsteps$marital_status[ethsteps$marital_status == 6] <- 2 #cohabiting
ethsteps$marital_status[ethsteps$marital_status == 88] <- NA 

ethsteps <- filter(ethsteps, sex == 2 & !is.na(weight))
```
```{r kenya clean}
knsteps <- select(knsteps_raw,
                   c(psu,
                     strata = stratum,
                     weight = wstep1, #there are also wstep2 and 3 - which one should I use (step 1 I believe as it refers to the weights for the interview)
                     urban_rural = residence, #rural = 1 and urban = 2
                     age = age,
                     sex = sex,
                     wealth,
                     #region = province, can't find the code for this
                     edu_label = C5,
                     marital_status = C7,
                     ever_cc_tested = CX1))

knsteps$ever_cc_tested[knsteps$ever_cc_tested == 7] <- NA #code don't know as NA
knsteps$ever_cc_tested[knsteps$ever_cc_tested == 2] <- 0
knsteps$Year <- 2015
knsteps$Country <- "Kenya"
knsteps$df <- "knsteps"

#Recode sex
knsteps$sex[knsteps$sex == "Men"] <- 1
knsteps$sex[knsteps$sex == "Women"] <- 2

#recode urban_rural so that urban = 1 and rural = 2
knsteps$urban_rural[knsteps$urban_rural == "Urban"] <- 1
knsteps$urban_rural[knsteps$urban_rural == "Rural"] <- 2

#recode education
knsteps$edu[knsteps$edu_label == "No formal schooling" | knsteps$edu_label == "Primary school incomplete"] <- 0 #no schooling completed
knsteps$edu[knsteps$edu_label == "Primary school completed" | knsteps$edu_label == "Secondary school incomplete"] <- 1 #primary education completed
knsteps$edu[knsteps$edu_label == "Secondary school completed" | knsteps$edu_label == "A-Level completed"] <- 2 #secondary education completed
knsteps$edu[knsteps$edu_label == "College/University completed" | knsteps$edu_label == "Post-graduate degree"] <- 3 #more than secondary schooling completed
knsteps$edu[knsteps$edu_label == "Refused"] <- NA 

#recode marital_status
knsteps$marital_status[knsteps$marital_status == 1] <- 0 #never married
knsteps$marital_status[knsteps$marital_status == 2] <- 1 #currently married
knsteps$marital_status[knsteps$marital_status == 3] <- 4 #separated or divorced
knsteps$marital_status[knsteps$marital_status == 5] <- 3 #widowed
knsteps$marital_status[knsteps$marital_status == 6] <- 2 #cohabiting
knsteps$marital_status[knsteps$marital_status == 88] <- NA 

#recode wealth
knsteps$wealth_quint[knsteps$wealth == "1 Poorest"] <- 1
knsteps$wealth_quint[knsteps$wealth == "2 Second"] <- 2
knsteps$wealth_quint[knsteps$wealth == "3 Middle"] <- 3
knsteps$wealth_quint[knsteps$wealth == "4 Fourth"] <- 4
knsteps$wealth_quint[knsteps$wealth == "5 Richest"] <- 5

knsteps <- filter(knsteps, sex == 2 & !is.na(weight))
```
```{r malawi clean}
mlsteps <- select(mlsteps_raw,
                   c(psu,
                     strata = stratum,
                     urban_rural = urbanrural, #char urban or rural
                     weight = wstep1,
                     age,
                     sex,
                     edu = c5,
                     marital_status = c7,
                     ever_cc_tested = cx1))
mlsteps$ever_cc_tested[mlsteps$ever_cc_tested == 77] <- NA #code don't know as NA
mlsteps$ever_cc_tested[mlsteps$ever_cc_tested == 2] <- 0
mlsteps$Year <- 2017
mlsteps$Country <- "Malawi"
mlsteps$df <- "mlsteps"

#Recode sex
mlsteps$sex[mlsteps$sex == "Men"] <- 1
mlsteps$sex[mlsteps$sex == "Women"] <- 2

#recode urban_rural so that urban = 1 and rural = 2
mlsteps$urban_rural[mlsteps$urban_rural == "Urban"] <- 1
mlsteps$urban_rural[mlsteps$urban_rural == "Rural"] <- 2

#recode education
mlsteps$edu[mlsteps$edu == 1] <- 0 #no schooling
mlsteps$edu[mlsteps$edu == 2 | mlsteps$edu == 3] <- 1 #primary education
mlsteps$edu[mlsteps$edu == 4] <- 2 #secondary education
mlsteps$edu[mlsteps$edu == 5] <- 3 #more than secondary schooling
mlsteps$edu[mlsteps$edu == 88] <- NA 

#recode marital_status
mlsteps$marital_status[mlsteps$marital_status == 1] <- 0 #never married
mlsteps$marital_status[mlsteps$marital_status == 2] <- 1 #currently married
mlsteps$marital_status[mlsteps$marital_status == 3] <- 4 #separated or divorced
mlsteps$marital_status[mlsteps$marital_status == 5] <- 3 #widowed
mlsteps$marital_status[mlsteps$marital_status == 6] <- 2 #cohabiting
mlsteps$marital_status[mlsteps$marital_status == 88] <- NA 

mlsteps <- filter(mlsteps, sex == 2 & !is.na(weight))
```
```{r senegal clean}
snsteps <- select(snsteps_raw,
                   c(psu,
                     strata = Stratum,
                     weight = wstep1,
                     interview_month = i4b,
                     Year = i4c,
                     agegr = c3r,
                     sex = c1, #1 = homme;2 = femme
                     edu = c5,
                     marital_status = c7,
                     ever_cc_tested = cx1))

snsteps$Country <- "Senegal"
snsteps$df <- "snsteps"

#recode education
snsteps$edu[snsteps$edu == 1] <- 0 #no schooling
snsteps$edu[snsteps$edu == 2 | snsteps$edu == 3] <- 1 #primary education
snsteps$edu[snsteps$edu == 4 | snsteps$edu == 5] <- 2 #secondary education
snsteps$edu[snsteps$edu == 6 | snsteps$edu == 7] <- 3 #more than secondary schooling
snsteps$edu[snsteps$edu == 88] <- NA 

#recode marital_status
snsteps$marital_status[snsteps$marital_status == 1] <- 0 #never married
snsteps$marital_status[snsteps$marital_status == 2] <- 1 #currently married
snsteps$marital_status[snsteps$marital_status == 3] <- 4 #separated or divorced
snsteps$marital_status[snsteps$marital_status == 5] <- 3 #widowed
snsteps$marital_status[snsteps$marital_status == 6] <- 2 #cohabiting
snsteps$marital_status[snsteps$marital_status == 88] <- NA 

#Recode age - this was inferred from the stats on the broad age group 
snsteps$agegr <- as.character(snsteps$agegr)
snsteps$agegr[snsteps$agegr == 1] <- "18-24"
snsteps$agegr[snsteps$agegr == 2] <- "25-29"
snsteps$agegr[snsteps$agegr == 3] <- "30-34"
snsteps$agegr[snsteps$agegr == 4] <- "35-39"
snsteps$agegr[snsteps$agegr == 5] <- "40-44"
snsteps$agegr[snsteps$agegr == 6] <- "45-49"
snsteps$agegr[snsteps$agegr == 7] <- "50-54"
snsteps$agegr[snsteps$agegr == 8] <- "55-59"
snsteps$agegr[snsteps$agegr == 9] <- "60-64"
snsteps$agegr[snsteps$agegr == 10] <- "65-69"

snsteps$Year <- as.numeric(snsteps$Year)

#cc screening questions
snsteps$ever_cc_tested[snsteps$ever_cc_tested == 77] <- NA #code don't know as NA
snsteps$ever_cc_tested[snsteps$ever_cc_tested == 2] <- 0

snsteps <- filter(snsteps, sex == 2 & !is.na(weight))

#find year at the midpoint of data
# for(i in 1:nrow(snsteps)){
#   snsteps$interview_date[i] <- snsteps$Year[i] + snsteps$interview_month[i]/12
# }
# median(snsteps$interview_date)
# mean(snsteps$interview_date)
# table(snsteps$interview_date)

# sum(table(snsteps_raw[snsteps_raw$sex == "Women",]$cx1))
# sum(table(snsteps$ever_cc_tested))
# table(is.na(snsteps$ever_cc_tested))
# nrow(filter(snsteps, agegr == 1 | agegr == 2))
# nrow(filter(snsteps, agegr == 3 | agegr == 4 | agegr == 5))
# nrow(filter(snsteps, agegr == 6 | agegr == 7 | agegr == 8))
# nrow(filter(snsteps, agegr == 9 | agegr == 10))
# nrow(snsteps)
# View(snsteps_raw)
# nrow(filter(snsteps_raw, c3r == 9 |c3r == 10))
# nrow(filter(snsteps_raw, !is.na(c3r)))
```
```{r sao tome and principe clean}
stpsteps <- select(stpsteps_raw,
                   c(psu,
                     strata = stratum,
                     weight = wstep1,
                     age,
                     sex,
                     ever_cc_tested = cx1))

stpsteps$Year <- 2019
stpsteps$Country <- "Sao Tome and Principe"
stpsteps$df <- "stpsteps"

#Recode sex
stpsteps$sex[stpsteps$sex == "Men"] <- 1
stpsteps$sex[stpsteps$sex == "Women"] <- 2

#cc screening questions
stpsteps$ever_cc_tested[stpsteps$ever_cc_tested == 77] <- NA #code don't know as NA
stpsteps$ever_cc_tested[stpsteps$ever_cc_tested == 2] <- 0

stpsteps <- filter(stpsteps, sex == 2 & !is.na(weight))

sum(table(stpsteps_raw[stpsteps_raw$sex == "Women",]$cx1))
sum(table(stpsteps$ever_cc_tested))
table(is.na(stpsteps$ever_cc_tested))
```
```{r uganda clean}
ugsteps <- select(ugsteps_raw,
                   c(psu,
                     urban_rural = stratum, #urban = 1; rural = 2
                     weight = wstep1,
                     age,
                     sex,
                     #region = province, can't find the code for this
                     c10a,
                     c10b,
                     c10c,
                     income = c11,
                     edu = c5,
                     marital_status = c7,
                     ever_cc_tested = cx1))
ugsteps$ever_cc_tested[ugsteps$ever_cc_tested == 77] <- NA #code don't know as NA
ugsteps$ever_cc_tested[ugsteps$ever_cc_tested == 2] <- 0
ugsteps$Year <- 2014
ugsteps$Country <- "Uganda"
ugsteps$df <- "ugsteps"

#Recode sex
ugsteps$sex[ugsteps$sex == "Men"] <- 1
ugsteps$sex[ugsteps$sex == "Women"] <- 2

#create annual income variable
ugsteps$annual_income <- NA
for(i in 1:nrow(ugsteps)){
  if(!is.na(ugsteps$c10a[i])){
    ugsteps$annual_income[i] <- ugsteps$c10a[i]*52
  }else if(!is.na(ugsteps$c10b[i])){
    ugsteps$annual_income[i] <- ugsteps$c10b[i]*12
  }else if(!is.na(ugsteps$c10c[i])){
    ugsteps$annual_income[i] <- ugsteps$c10c[i]
  }
}

#recode education
ugsteps$edu[ugsteps$edu == 1] <- 0 #no schooling completed
ugsteps$edu[ugsteps$edu == 2 ] <- 1 #primary education completed
ugsteps$edu[ugsteps$edu == 3 | ugsteps$edu == 4 | ugsteps$edu == 5] <- 2 #secondary education completed
ugsteps$edu[ugsteps$edu == 6 | ugsteps$edu == 7] <- 3 #more than secondary schooling completed
ugsteps$edu[ugsteps$edu == 88] <- NA 

#recode marital_status
ugsteps$marital_status[ugsteps$marital_status == 1] <- 0 #never married
ugsteps$marital_status[ugsteps$marital_status == 2] <- 1 #currently married
ugsteps$marital_status[ugsteps$marital_status == 3] <- 4 #separated or divorced
ugsteps$marital_status[ugsteps$marital_status == 5] <- 3 #widowed
ugsteps$marital_status[ugsteps$marital_status == 6] <- 2 #cohabiting
ugsteps$marital_status[ugsteps$marital_status == 88] <- NA 

ugsteps <- filter(ugsteps, sex == 2 & !is.na(weight))
```
```{r zambia clean}
zmsteps <- select(zmsteps_raw,
                   c(psu,
                     urban_rural = stratum, #rural = 1; urban = 2
                     weight = wstep1,
                     age,
                     sex,
                     c10, 
                     c10type,
                     income = c11,
                     edu = c5,
                     marital_status = c7,
                     ever_cc_tested = cx1))
zmsteps$ever_cc_tested[zmsteps$ever_cc_tested == 77] <- NA #code don't know as NA
zmsteps$ever_cc_tested[zmsteps$ever_cc_tested == 2] <- 0
zmsteps$Year <- 2017
zmsteps$Country <- "Zambia"
zmsteps$df <- "zmsteps"

#Recode sex
zmsteps$sex[zmsteps$sex == "Men"] <- 1
zmsteps$sex[zmsteps$sex == "Women"] <- 2

#recode urban_rural so that urban = 1 and rural = 2
zmsteps$urban_rural[zmsteps$urban_rural == 1] <- 0
zmsteps$urban_rural[zmsteps$urban_rural == 2] <- 1
zmsteps$urban_rural[zmsteps$urban_rural == 0] <- 2

#recode education
zmsteps$edu[zmsteps$edu == 1 | zmsteps$edu == 2] <- 0 #no schooling completed
zmsteps$edu[zmsteps$edu == 3] <- 1 #primary education completed
zmsteps$edu[zmsteps$edu == 4 | zmsteps$edu == 5] <- 2 #secondary education completed
zmsteps$edu[zmsteps$edu == 6 | zmsteps$edu == 7] <- 3 #more than secondary schooling completed
zmsteps$edu[zmsteps$edu == 88] <- NA 

#recode marital_status
zmsteps$marital_status[zmsteps$marital_status == 1] <- 0
zmsteps$marital_status[zmsteps$marital_status == 2] <- 1
zmsteps$marital_status[zmsteps$marital_status == 3] <- 4 #will assume that those who report in a steady relationship but not married or those who are single have never been married
zmsteps$marital_status[zmsteps$marital_status == 5] <- 3
zmsteps$marital_status[zmsteps$marital_status == 6] <- 2
zmsteps$marital_status[zmsteps$marital_status == 88] <- NA #will assume civil union is the same as married

zmsteps <- filter(zmsteps, sex == 2 & !is.na(weight))
```

```{r missing data}
a <- filter(zmsteps_raw, sex == "Women")
table(a$cx1)
nrow(a)
sum(table(a$cx1))

#View(zmsteps_raw[!is.na(zmsteps_raw$cx1),c("sex", "cx1")])
names(knsteps_raw)[names(knsteps_raw) == "CX1"] <- "cx1"
names(ethsteps_raw)[names(ethsteps_raw) == "c1"] <- "sex"
names(ethsteps_raw)[names(ethsteps_raw) == "c3"] <- "age"
steps_list <- list(bnsteps_raw, btsteps_raw, ethsteps_raw, knsteps_raw, mlsteps_raw, szsteps_raw, ugsteps_raw, zmsteps_raw)
names(steps_list) <- c("bnsteps", "btsteps", "ethsteps", "knsteps", "mlsteps", "szsteps", "ugsteps", "zmsteps")

steps_list <- list(snsteps_raw)
names(steps_list) <- c("snsteps")
age.groups = data.frame(l_age = seq(15, 65, 5), u_age = c(seq(19, 64, 5), 1000))
A <- nrow(age.groups)
for(i in 1:length(steps_list)){
  for(n in 1:nrow(steps_list[[i]])){
    for(a in 1:A){
      if(!is.na(steps_list[[i]]$age[n]) & age.groups$l_age[a] <= steps_list[[i]]$age[n] & age.groups$u_age[a] >= steps_list[[i]]$age[n]){
        agegr <- paste0(age.groups$l_age[a], "-", age.groups$u_age[a])
        steps_list[[i]]$agegr[n] <- agegr
      }
    }
  }
}

steps_list <- list(snsteps_raw)
names(steps_list) <- c("snsteps")
names(steps_list[[1]])[names(steps_list[[1]]) == "c1"] <- "sex"
names(steps_list[[1]])[names(steps_list[[1]]) == "c3r"] <- "agegr"
dat_missing <- data.frame(Survey = NA,
                 agegr = NA,
                 elg_resp = NA,
                 resp = NA,
                 dk = NA,
                 missing = NA)
n=1
for(i in 1:length(steps_list)){
  for(a in 1:length(sort(unique(steps_list[[i]]$agegr)))){
    gr <- sort(unique(steps_list[[i]]$agegr))[a]
    df <- filter(steps_list[[i]], sex == "Women" | sex == 2)
    df <- filter(df, agegr == gr)
    id <- names(steps_list)[i]
    tbl <- table(df$cx1)
    df_tbl <- data.frame(tbl)
    
    elg_resp <- nrow(df)
    resp <- sum(tbl)
    missing <- elg_resp - resp
    dk <- df_tbl[df_tbl$Var1 == 77 , 2]
    if(length(dk) <= 0){
      dk <- 0
    }
    dat_missing[n, ] <- c(id, gr, elg_resp, resp, dk, missing)
    print(id); print(gr); print(tbl)
    n=n+1
  }
}
dat_missing$agegr <- factor(dat_missing$agegr, levels = c("15-19", "20-24", "25-29", "30-34", 
                                                          "35-39", "40-44", "45-49", "50-54", 
                                                          "55-59", "60-64", "65-1000"))
for(i in 1:length(steps_list)){
  a <- filter(dat_missing, Survey == names(steps_list)[i])
  print(sum(as.numeric(a$missing)))
}
```

```{r save}
#load("Cleaned STEPS")
save(bnsteps, btsteps, cpvsteps, ethsteps, knsteps, mlsteps, snsteps, stpsteps, szsteps, ugsteps, zmsteps,
     file = "Cleaned STEPS")
```
