---
title: "Pooled Surveys"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import}
library(haven)
library(dplyr)
library(survey)
library(ggplot2)
library(readxl)
library(gt)
library(knitr)
library(kableExtra)
source("df_functions.R")

surveys <- read_excel("surveys.xlsx", sheet = 1)
all_q <- read_excel("surveys.xlsx", sheet = 2)
eco_det <- read_excel("surveys.xlsx", sheet = 4)
# 
load("Cleaned Pooled Surveys")
load("Cleaned Indv Surveys")
load("Cleaned DHS")
load("Cleaned KAIS")
load("Cleaned PHIA")
load("Cleaned STEPS")
load("Cleaned SABSSM")
load("Cleaned SAGE")
load("Cleaned WHS")

mean(na.omit(cpvsteps$age_first_tested))
```
```{r merge datasets}
#DHS
dhs_list <- list(bndhs,
                 cidhs,
                 cmdhs,
                 kedhs,
                 ls9dhs,
                 ls14dhs,
                 nm0dhs,
                 nm13dhs,
                 sadhs,
                 tzdhs,
                 zwdhs)
                 
dhs <- Reduce(
  function(x, y, all = T)
  merge(x, y, all = T),
  dhs_list
)
dhs$Survey <- "DHS"

#PHIA
phia_list <- list(ethphia,
                  mlphia,
                  rwphia,
                  tzphia,
                  zmphia,
                  zwphia)

phia <- Reduce(
  function(x, y, all = T)
  merge(x, y, all = T),
  phia_list
)
phia$Survey <- "PHIA"

#SAGE
sage_list <- list(ghsage,
                   sasage)

sage <- Reduce(
  function(x, y, all = T)
  merge(x, y, all = T),
  sage_list
)
sage$Survey <- "SAGE"

#STEPS
steps_list <- list(bnsteps,
                   btsteps,
                   cpvsteps,
                   ethsteps,
                   knsteps,
                   mlsteps,
                   snsteps,
                   stpsteps,
                   szsteps,
                   ugsteps,
                   zmsteps)

steps <- Reduce(
  function(x, y, all = T)
  merge(x, y, all = T),
  steps_list
)
steps$Survey <- "STEPS"

#WHS
abrv = c("bf", "ch", "ci", "cm", "cn", "eth",
         "gh", "kn", "ma", "ml", "mrt", "mus",
         "nm", "sa", "sn", "sz", "zm", "zw")

countries = c("Burkina Faso", "Chad", "Cote d'Ivoire", "Comoros", "Congo (Rep)", "Ethiopia", "Ghana", "Kenya", "Mali", "Malawi", "Mauritania", "Mauritius", "Namibia", "South Africa", "Senegal", "Eswatini", "Zambia", "Zimbabwe")

whs <- list(bfwhs, chwhs, ciwhs, cmwhs, cnwhs, ethwhs, ghwhs,
               knwhs, mawhs, mlwhs, mrtwhs, muswhs, nmwhs,
               sawhs, snwhs, szwhs, zmwhs, zwwhs)

whs_names <- c("bfwhs", "chwhs", "ciwhs", "cmwhs", "cnwhs", "ethwhs", "ghwhs",
               "knwhs", "mawhs", "mlwhs", "mrtwhs", "muswhs", "nmwhs",
               "sawhs", "snwhs", "szwhs", "zmwhs", "zwwhs")

names(whs) <- countries

#adding country and df variable
for(i in 1:length(whs)){
  whs[[i]]$Country <- countries[i]
  whs[[i]]$df <- paste0(abrv[i], "whs")
  #print(nrow(whs_list[[i]]))
}

#if list already created in "All WHS.R"
whs_list <- whs

whs <- Reduce(
  function(x, y, all = T)
  merge(x, y, all = T),
  whs_list
)
whs$Survey <- "WHS"

sabssm$Survey <- "SABSSM"
sabssm$df <- "sabssm"

kais$Survey <- "KAIS"
kais$df <- "kais"

surveys_list <- list(dhs, phia, sage, steps, whs, sabssm, kais)

pooled_surveys <- Reduce(
  function(x, y, all = T)
  merge(x, y, all = T),
  surveys_list
)

store <- pooled_surveys

pooled_surveys$Year <- as.numeric(pooled_surveys$Year)
surveys <- unique(surveys[,c("Region", "Region_unaids", "Country", "Survey")]) #unique bc there's 2 DHS surveys from Lesotho
pooled_surveys <- left_join(pooled_surveys, surveys)
a <- left_join(pooled_surveys, surveys)

names(pooled_surveys)[names(pooled_surveys) == "psu"] <- "psu_raw"
pooled_surveys$psu <- paste0(pooled_surveys$df, "-", pooled_surveys$psu_raw)
View(unique(pooled_surveys[,c("df", "Country", "Region")]))

#adding eco determinants
eco_det <- eco_det[,c("df", "GDP per capita (USD)")]
pooled_surveys <- left_join(pooled_surveys, eco_det)
#View(pooled_surveys[,c("Country", "Year", "df", "GDP per capita (USD)")])

#View(pooled_surveys[pooled_surveys$df == "ghsage",])
```
```{r save dataframes}
save(dhs, phia, sage, steps, whs, sabssm, kais,
     pooled_surveys, 
     dhs_list, phia_list, sage_list, steps_list, whs_list, 
     file = "Cleaned Pooled Surveys")

save(bndhs, cidhs, cmdhs, kedhs, ls9dhs, ls14dhs, nm0dhs, nm13dhs, sadhs, tzdhs, zwdhs,
     ethphia, mlphia, rwphia, tzphia, zmphia, zwphia,
     bfwhs, sabssm, bfwhs, chwhs, ciwhs, cmwhs, cnwhs, ethwhs, ghwhs, 
     knwhs, mawhs, mlwhs, mrtwhs, muswhs, nmwhs, sawhs, snwhs, szwhs, zmwhs, zwwhs, 
     bnsteps, btsteps, cpvsteps, ethsteps, knsteps, mlsteps, stpsteps, szsteps, ugsteps, zmsteps,
     sabssm,
     kais,
     ghsage, sasage,
     file = "Cleaned Indv Surveys")
```
```{r tables}
#survey size characteristics
nrow(dat_anytest_3y)
nrow(dat_anytest_ever)
nrow(dat_anytest_all)
nrow(dat_anytest)
overall <- filter(dat_anytest, !is.na(any_test_past_3y) | !is.na(any_test_ever))
past_3y <- filter(dat_anytest, !is.na(any_test_past_3y))
ever <- filter(dat_anytest, !is.na(any_test_ever))

#obtain values from tabulations
bfsteps <- c(0.079, 0.056, 0.102) #estimate for ages 30-49 will assume its the same for all age groups between those ages
  
  p_bf <- bfsteps[1]
  lci_bf <- bfsteps[2]
  uci_bf <- bfsteps[2]
  
  bfsteps_den <- round(p_bf*(1-p_bf)/((p_bf - lci_bf)/1.96)^2)
  bfsteps_num <- round(bfsteps_den*p_bf)
  
  df_bfsteps <- data.frame(agegr = c("30-34", "35-39", "40-44", "45-49"),
                           prob = rep(bfsteps[1], 4),
                           den = round(rep(bfsteps_den/4, 4)),
                           num = round(rep(bfsteps_num/4, 4)))
  
  #add values from Mozambique STEPS tabulations
  mzsteps_3055 <- 0.035
  mzsteps_den <- rep(871/5, 5)
  
  df_mzsteps <- data.frame(agegr = c("30-34", "35-39", "40-44", "45-49"),
                           prob = rep(mzsteps_3055, 4),
                           den = round(c(rep(871/5, 4))),
                           num = round(c(rep(871/5*mzsteps_3055, 4))))
  
  #add values from zw20phia
  zw20phia <- c(0.27, 0.364, 0.325, 0.382, 0.429)
  zw20phia_den <- c(168, 257, 318, 307, 389)
  zw20phia_num <- zw20phia*zw20phia_den
  
  df_zw20phia <- data.frame(agegr = c("25-29", "30-34", "35-39", "40-44", "45-49"),
                           prob = zw20phia,
                           den = round(zw20phia_den),
                           num = round(zw20phia_num))
  
  #add extra columns to data frames to match dat_timetrends_gr
  df_bfsteps$df <- "bfsteps"
  df_bfsteps$time_length <- "ever"
  df_bfsteps$Country <- "Burkina Faso"
  df_bfsteps$hivstat <- NA
  
  df_mzsteps$df <- "mzsteps"
  df_mzsteps$time_length <- "ever"
  df_mzsteps$Country <- "Mozambique"
  df_mzsteps$hivstat <- NA
  
  df_zw20phia$df <- "zw20phia"
  df_zw20phia$time_length <- "ever"
  df_zw20phia$Country <- "Zimbabwe"
  df_zw20phia$hivstat <- 1

  df_to_add <- rbind(df_bfsteps, df_mzsteps, df_zw20phia)
  df_to_add <- select(df_to_add, -prob)
  
overall_resp <- nrow(overall) + sum(df_to_add$den)
length(unique(a$df));length(unique(a$Country)) + 1

#look at by hiv status
#b <- filter(a, !is.na(hivstat));length(unique(b$df));length(unique(b$Country));nrow(b)

unique_df_overall <- rbind(unique(overall[,c("Country", "df")]), unique(df_to_add[,c("Country", "df")]))
count_1_overall <- rownames(filter(data.frame(num = table(unique_df_overall$Country) == 1), num == T)) 
count_2_overall <- rownames(filter(data.frame(num = table(unique_df_overall$Country) == 2), num == T)) 
count_3_overall <- rownames(filter(data.frame(num = table(unique_df_overall$Country) >= 3), num == T)) 

unique_df_past_3y <- unique(past_3y[,c("Country", "df")])
count_1_past_3y <- rownames(filter(data.frame(num = table(unique_df_past_3y$Country) == 1), num == T)) 
count_2_past_3y <- rownames(filter(data.frame(num = table(unique_df_past_3y$Country) == 2), num == T)) 
count_3_past_3y <- rownames(filter(data.frame(num = table(unique_df_past_3y$Country) >= 3), num == T)) 

unique_df_ever <- rbind(unique(ever[,c("Country", "df")]), unique(df_to_add[,c("Country", "df")]))
count_1_ever <- rownames(filter(data.frame(num = table(unique_df_ever$Country) == 1), num == T)) 
count_2_ever <- rownames(filter(data.frame(num = table(unique_df_ever$Country) == 2), num == T)) 
count_3_ever <- rownames(filter(data.frame(num = table(unique_df_ever$Country) >= 3), num == T)) 

df_1_overall <- overall[overall$Country %in% count_1_overall,];length(unique(df_1_overall$df));length(unique(df_1_overall$Country));nrow(df_1_overall) 
df_2_overall <- overall[overall$Country %in% count_2_overall,];length(unique(df_2_overall$df));length(unique(df_2_overall$Country));nrow(df_2_overall) 
df_3_overall <- overall[overall$Country %in% count_3_overall,];length(unique(df_3_overall$df));length(unique(df_3_overall$Country));nrow(df_3_overall) 

df_1_past_3y <- past_3y[past_3y$Country %in% count_1_past_3y,];length(unique(df_1_past_3y$df));length(unique(df_1_past_3y$Country));nrow(df_1_past_3y) 
df_2_past_3y <- past_3y[past_3y$Country %in% count_2_past_3y,];length(unique(df_2_past_3y$df));length(unique(df_2_past_3y$Country));nrow(df_2_past_3y) 
df_3_past_3y <- past_3y[past_3y$Country %in% count_3_past_3y,];length(unique(df_3_past_3y$df));length(unique(df_3_past_3y$Country));nrow(df_3_past_3y) 

df_1_ever <- ever[ever$Country %in% count_1_ever,];length(unique(df_1_ever$df));length(unique(df_1_ever$Country));nrow(df_1_ever) 
df_2_ever <- ever[ever$Country %in% count_2_ever,];length(unique(df_2_ever$df));length(unique(df_2_ever$Country));nrow(df_2_ever) 
df_3_ever <- ever[ever$Country %in% count_3_ever,];length(unique(df_3_ever$df));length(unique(df_3_ever$Country));nrow(df_3_ever) 

cc_survey_char <- data.frame(Type = c("Only Past 3Y", "Only Ever", "Past 3Y and Ever", "Overall"),
                             N = c(30789, 73946 + bfsteps_den + snsteps_den, 147176, 251911 + bfsteps_den + snsteps_den),
                             Surveys = c(18, 15, 13, 46),
                             Countries = c(18, 12, 10, 25),
                             Years = c("2003", "2000-2019", "2009-2019", "2000-2019"))
cc_survey_char2 <- data.frame(Surveys_Per_Country = c(rep(1,3), rep(2,3), rep("3+",3), rep("Any", 3)),
                                           Type = rep(c("Past 3Y", "Ever", "Overall"), 4),
                                           N = c(nrow(df_1_past_3y), nrow(df_1_ever) + sum(df_mzsteps$den), nrow(df_1_overall) + sum(df_mzsteps$den), 
                                                 nrow(df_2_past_3y), nrow(df_2_ever) + sum(df_bfsteps$den), nrow(df_2_overall) + sum(df_bfsteps$den), 
                                                 nrow(df_3_past_3y), nrow(df_3_ever) + sum(df_zw20phia$den), nrow(df_3_overall) + sum(df_zw20phia$den), 
                                                 nrow(past_3y), nrow(ever) + sum(df_to_add$den), nrow(overall) + sum(df_to_add$den)), 
                                           Countries = c(length(count_1_past_3y), length(count_1_ever), length(count_1_overall),
                                                         length(count_2_past_3y), length(count_2_ever), length(count_2_overall), 
                                                         length(count_3_past_3y), length(count_3_ever), length(count_3_overall),
                                                         length(unique(past_3y$Country)), length(unique(ever$Country)) + 1, length(unique(overall$Country)) + 1),
                                           Surveys = c(length(unique(df_1_past_3y$df)), length(unique(df_1_ever$df)) + 1, length(unique(df_1_overall$df)) + 1, 
                                                       length(unique(df_2_past_3y$df)), length(unique(df_2_ever$df)) + 1, length(unique(df_2_overall$df)) + 1,
                                                       length(unique(df_3_past_3y$df)), length(unique(df_3_ever$df)) + 1, length(unique(df_3_overall$df)) + 1, 
                                                       length(unique(past_3y$df)), length(unique(ever$df)) + 3, length(unique(overall$df)) + 3),
                                           Years = c("2003-2018", "2011-2019", "2003-2019", 
                                                     "2003-2018", "2000-2018", "2000-2018",
                                                     "2003-2016", "2012-2020", "2000-2020",
                                                     "2003-2019", "2000-2020", "2000-2020"))
names(cc_survey_char2)[names(cc_survey_char2) == "Surveys_Per_Country"] <- "Surveys Per Country"
cc_survey_char2$Type <- factor(cc_survey_char2$Type, levels = c("Past 3Y", "Ever", "Overall"))
x <- with(cc_survey_char2, cc_survey_char2[order(cc_survey_char2$Type),])

cc_survey_char2_fr <- data.frame(Surveys_Per_Country = c(rep(1,3), rep(2,3), rep("3+",3), rep("Tout", 3)),
                                           Type = rep(c("3a", "À vie", "Tout"), 4),
                                           N = c(76613, 65981, 67788, 
                                                 55623, 129830 + bfsteps_den + snsteps_den, 38944 + bfsteps_den + snsteps_den, 
                                                 45729, 25311, 145179,
                                                 177965, 221122 + bfsteps_den + snsteps_den, 251911 + bfsteps_den + snsteps_den),
                                           Pays = c(17, 9, 12, 
                                                         4, 8, 6, 
                                                         2, 1, 7, 
                                                         23, 18, 25),
                                           Enquêtes = c(17, 9, 12, 
                                                             8, 16, 12, 
                                                             6, 3, 22, 
                                                             31, 25, 46),
                                           Années = c("2003-2018", "2011-2019", "2003-2019", 
                                                     "2003-2018", "2000-2018", "2000-2018",
                                                     "2003-2016", "2012-2015", "2000-2017",
                                                     "2003-2019", "2000-2019", "2000-2019"))
names(cc_survey_char2_fr)[names(cc_survey_char2_fr) == "Surveys_Per_Country"] <- "Enquêtes par Pays"
cc_survey_char2_fr$Type <- factor(cc_survey_char2_fr$Type, levels = c("3a", "À vie", "Tout"))
x_fr <- with(cc_survey_char2_fr, cc_survey_char2_fr[order(cc_survey_char2_fr$Type),])

kbl(cc_survey_char2, align = "c") %>%
  kable_classic()
kbl(x_fr, align = "c") %>%
  kable_classic()
ltc_survey_char <- data.frame(Type = c("Received result", "Had follow up appointment", "Treated", "Treated same day"),
                              N = c(6642, 618, 129, 96),
                              Surveys = c(6, 5, 3, 3))

kbl(ltc_survey_char, align = "c") %>%
  kable_classic()

a <- filter(dat_anytest, !is.na(any_test_past_3y) | !is.na(any_test_ever));length(unique(a$df));length(unique(a$Country));nrow(a)
b <- filter(a,!is.na(hivstat));length(unique(b$df));length(unique(b$Country));nrow(b)
unique_df <- unique(a[,c("Country", "df")])

cc_survey_char_hiv <- data.frame(HIV = c("Yes", "No"),
                                 Countries = c("12", "16"),
                                 Surveys = c("16", "36"))

names(cc_survey_char_hiv)[names(cc_survey_char_hiv) == "HIV"] <- "HIV Biomarker Data"
kbl(cc_survey_char_hiv, align = "c") %>%
  kable_classic()

cc_survey_char_hiv_fr <- data.frame(HIV = c("Oui", "Non"),
                                 Pays = c("12", "13"),
                                 Enquêtes = c("15", "31"))

names(cc_survey_char_hiv_fr)[names(cc_survey_char_hiv_fr) == "HIV"] <- "Données sur les biomarqueurs du VIH"
kbl(cc_survey_char_hiv_fr, align = "c") %>%
  kable_classic()

agegr1524 <- nrow(filter(a, age>=15 & age <=24))
agegr2549 <- nrow(filter(a, age>=25 & age <=49)) + sum(df_to_add$den)
agegr50 <- nrow(filter(a, age>=50 & age <=1000))
agegrall <- nrow(a) + sum(df_to_add$den)
cc_survey_age <- data.frame(Age.Group = c("15-24", "25-49", "50+", "Overall"),
           N = c(agegr1524, agegr2549, agegr50 , agegrall))
names(cc_survey_age)[names(cc_survey_age) == "Age.Group"] <- "Age Group"
kbl(cc_survey_age, align = "c") %>%
  kable_classic()

#determinants characteristics
det_char <- data.frame(Determinant = c("Urban/Rural", 
                                       "HIV Status", 
                                       "Health Insurance", 
                                       "Controlling Behaviours",
                                       "Education",
                                       "Wealth Quintile",
                                       "Sexual Activity Level",
                                       "Marital Status"),
                       N = c(177649, 115034, 49496, 12343, 174926, 132757, 63464, 177332),
                       Surveys = c(31, 12, 6, 3, 31, 12, 8, 31))
kbl(det_char, align = "c") %>%
  kable_classic()
```

```{r survey characteristics}
hiv_df_gr <- readRDS("hiv_dat_timetrends_gr.rds")

#countries with 2 or more surveys
table(unique(hiv_df_gr[,c("Country", "df")])$Country)
table((table(unique(hiv_df_gr[,c("Country", "df")])$Country) >= 2))

#countries with biomarker data
length(unique(hiv_df_gr[hiv_df_gr$'HIV Biomarker' == "Y", "Country"]))
length(unique(hiv_df_gr[hiv_df_gr$'HIV Biomarker' == "Y", "df"]))

#countries with each screening interval
a <- unique(hiv_df_gr[,c("df", "time_length")])
b <- data.frame(multi = table(a$df) >= 2, df = names(table(a$df)))

c <- left_join(a, b)

length(table(c[c$multi == T,]$df))
length(table(c[c$multi == F & c$time_length == "3y",]$df))
length(table(c[c$multi == F & c$time_length == "ever",]$df))

#number of female participants for each analysis
#screening
nrow(dat_anytest_3y) #load these dataframes from the group logistic regression.R code 
nrow(dat_anytest_ever)
nrow(dat_anytest_all)
nrow(dat_anytest)
overall <- filter(dat_anytest, !is.na(any_test_past_3y) | !is.na(any_test_ever))
past_3y <- filter(dat_anytest, !is.na(any_test_past_3y))
ever <- filter(dat_anytest, !is.na(any_test_ever))

#obtain values from tabulations
bfsteps <- c(0.079, 0.056, 0.102) #estimate for ages 30-49 will assume its the same for all age groups between those ages
  
  p_bf <- bfsteps[1]
  lci_bf <- bfsteps[2]
  uci_bf <- bfsteps[2]
  
  bfsteps_den <- round(p_bf*(1-p_bf)/((p_bf - lci_bf)/1.96)^2)
  bfsteps_num <- round(bfsteps_den*p_bf)
  
  df_bfsteps <- data.frame(agegr = c("30-34", "35-39", "40-44", "45-49"),
                           prob = rep(bfsteps[1], 4),
                           den = round(rep(bfsteps_den/4, 4)),
                           num = round(rep(bfsteps_num/4, 4)))
  
  #add values from Mozambique STEPS tabulations
  mzsteps_3055 <- 0.035
  mzsteps_den <- rep(871/5, 5)
  
  df_mzsteps <- data.frame(agegr = c("30-34", "35-39", "40-44", "45-49"),
                           prob = rep(mzsteps_3055, 4),
                           den = round(c(rep(871/5, 4))),
                           num = round(c(rep(871/5*mzsteps_3055, 4))))
  
  #add values from zw20phia
  zw20phia <- c(0.27, 0.364, 0.325, 0.382, 0.429)
  zw20phia_den <- c(168, 257, 318, 307, 389)
  zw20phia_num <- zw20phia*zw20phia_den
  
  df_zw20phia <- data.frame(agegr = c("25-29", "30-34", "35-39", "40-44", "45-49"),
                           prob = zw20phia,
                           den = round(zw20phia_den),
                           num = round(zw20phia_num))
  
  #add extra columns to data frames to match dat_timetrends_gr
  df_bfsteps$df <- "bfsteps"
  df_bfsteps$time_length <- "ever"
  df_bfsteps$Country <- "Burkina Faso"
  df_bfsteps$hivstat <- NA
  
  df_mzsteps$df <- "mzsteps"
  df_mzsteps$time_length <- "ever"
  df_mzsteps$Country <- "Mozambique"
  df_mzsteps$hivstat <- NA
  
  df_zw20phia$df <- "zw20phia"
  df_zw20phia$time_length <- "ever"
  df_zw20phia$Country <- "Zimbabwe"
  df_zw20phia$hivstat <- 1

  df_to_add <- rbind(df_bfsteps, df_mzsteps, df_zw20phia)
  df_to_add <- select(df_to_add, -prob)
  
overall_resp <- nrow(overall) + sum(df_to_add$den)
length(unique(a$df));length(unique(a$Country)) + 1

#isolate to only those 25-49
overall_2549 <- filter(overall, age >= 25 & age <= 49)

#number of women used for analysis with screening
nrow(overall_2549) + sum(df_to_add$den)

#treatment
overall_treatment <- filter(dat_anytest, !is.na(cc_treated))
nrow(overall_treatment)
table(overall_treatment$age)

#percent of the female population
countries <- unique(pooled_surveys$Country)

pop_age <- read_excel("pop_age2020.xlsx", sheet = 2) #i should change this so i can use the age structure for every year
  colnames(pop_age) <- pop_age[1,]
  pop_age <- pop_age[-c(1:4), -c(1, 3:5)]
  pop_age[,-1] <- lapply(pop_age[,-1], as.numeric)
  #isolate to only those of a certain age
  pop_age <- pop_age[,c("Location", agegr)] #rmbr to use the age groups that were used for the model even if the post-model analysis uses other age groups
  pop_age_long <- pivot_longer(pop_age, cols = -1, names_to = "agegr", values_to = "f_pop")
  pop_age_long$agegr <- as.numeric(factor(pop_age_long$agegr))
  names(pop_age_long)[names(pop_age_long) == "Location"] <- "Country"
  #clean up data to match 
  pop_age_long$Country[pop_age_long$Country == "Cabo Verde"] <- "Cape Verde"
  pop_age_long$Country[pop_age_long$Country == "Congo"] <- "Congo (Rep)"
  pop_age_long$Country[pop_age_long$Country == "Côte d'Ivoire"] <- "Cote d'Ivoire"
  pop_age_long$Country[pop_age_long$Country == "United Republic of Tanzania"] <- "Tanzania"
 
  View(pop_age)
  read_excel("pop_age2020_ssa.xlsx", sheet = 2)
  pop_age_ssa <- 42478 + 36391 + 30740 + 25006 + 20227
  pop_age_count <- sum(pop_age_long[pop_age_long$Country %in% countries,]$f_pop)
  
  pop_age_count/pop_age_ssa
  
  #sample size of women 25-49 for each age group
  agegr <- c("25-29", "30-34", "35-39", "40-44", "45-49")
  a <- hiv_df_gr[hiv_df_gr$agegr %in% agegr, ]
  
  b <- a %>%
    group_by(df) %>%
    summarise(df, Country, Region, Year, sum(denominator_original))
  
  View(unique(b))
```

```{r proportion with pap smear/cctest in past 1y/3y function}
papsmearpast1y <- function(df, age1, age2){
  sub_df <- filter(df, age >= age1 & age <= age2 & !is.na(pap_smear_past_1y))
  
  if(nrow(sub_df) <= 1){
    return(data.frame("Mean" = NA, "Lower" = NA, "Upper" = NA))
    
  }else{
    if(length(sub_df$strata) != 0){
      design <- svydesign(data = sub_df, weights = ~weight, id = ~psu, strata = ~strata, nest = T) 
      m <- svyciprop(~pap_smear_past_1y, design = design)
      ci <- confint(m)
  
      return(data.frame("Mean" = as.numeric(m[1]), "Lower" = ci[1], "Upper" = ci[2]))
    } else{
      design <- svydesign(data = sub_df, weights = ~weight, id = ~psu) #may need to add strata
      m <- svyciprop(~pap_smear_past_1y, design = design)
      ci <- confint(m)
  
      return(data.frame("Mean" = as.numeric(m[1]), "Lower" = ci[1], "Upper" = ci[2]))
    }
  }
}
papsmearpast3y <- function(df, age1, age2){
  sub_df <- filter(df, age >= age1 & age <= age2 & !is.na(pap_smear_past_3y))
  
  if(nrow(sub_df) <= 1){
    return(data.frame("Mean" = NA, "Lower" = NA, "Upper" = NA))
    
  }else{
    if(length(sub_df$strata) != 0){
      design <- svydesign(data = sub_df, weights = ~weight, id = ~psu, strata = ~strata, nest = T)
      m <- svyciprop(~pap_smear_past_3y, design = design)
      ci <- confint(m)
  
      return(data.frame("Mean" = as.numeric(m[1]), "Lower" = ci[1], "Upper" = ci[2]))
    } else{
      design <- svydesign(data = sub_df, weights = ~weight, id = ~psu) #may need to add strata
      m <- svyciprop(~pap_smear_past_3y, design = design)
      ci <- confint(m)
  
      return(data.frame("Mean" = as.numeric(m[1]), "Lower" = ci[1], "Upper" = ci[2]))
    }
  }
}
cctestpast1y <- function(df, age1, age2){
  sub_df <- filter(df, age >= age1 & age <= age2 & !is.na(cc_test_past_1y))
  
  if(nrow(sub_df) <= 1){
    return(data.frame("Mean" = NA, "Lower" = NA, "Upper" = NA))
    
  }else{
    if(length(sub_df$strata) != 0){
      design <- svydesign(data = sub_df, weights = ~weight, id = ~psu, strata = ~strata, nest = T) 
      m <- svyciprop(~cc_test_past_1y, design = design)
      ci <- confint(m)
  
      return(data.frame("Mean" = as.numeric(m[1]), "Lower" = ci[1], "Upper" = ci[2]))
    } else{
      design <- svydesign(data = sub_df, weights = ~weight, id = ~psu) #may need to add strata
      m <- svyciprop(~cc_test_past_1y, design = design)
      ci <- confint(m)
  
      return(data.frame("Mean" = as.numeric(m[1]), "Lower" = ci[1], "Upper" = ci[2]))
    }
  }
}
cctestpast3y <- function(df, age1, age2){
  sub_df <- filter(df, age >= age1 & age <= age2 & !is.na(cc_test_past_3y))
  
  if(nrow(sub_df) <= 1){
    return(data.frame("Mean" = NA, "Lower" = NA, "Upper" = NA))
    
  }else{
    if(length(sub_df$strata) != 0){
      design <- svydesign(data = sub_df, weights = ~weight, id = ~psu, strata = ~strata, nest = T)
      m <- svyciprop(~cc_test_past_3y, design = design)
      ci <- confint(m)
  
      return(data.frame("Mean" = as.numeric(m[1]), "Lower" = ci[1], "Upper" = ci[2]))
    } else{
      design <- svydesign(data = sub_df, weights = ~weight, id = ~psu) #may need to add strata
      m <- svyciprop(~cc_test_past_3y, design = design)
      ci <- confint(m)
  
      return(data.frame("Mean" = as.numeric(m[1]), "Lower" = ci[1], "Upper" = ci[2]))
    }
  }
}
```
```{r Lesotho explore}
table(ls9dhs$ever_had_pap_smear)
table(ls9dhs$ever_had_pap_smear, ls9dhs$pap_smear_past_3y)
table(ls9dhs$pap_smear_past_1y); table(ls9dhs$pap_smear_past_3y); table(ls9dhs$ever_had_pap_smear)
table(ls14dhs$pap_smear_past_1y); table(ls14dhs$pap_smear_past_3y); table(ls14dhs$ever_had_pap_smear)

age.groups <- data.frame(15:49, 15:49)
df <- data.frame(agegr=15:49)
everhadpapsmear_ls9dhs <- df_age_fig(age.groups, ls9dhs, everhadpapsmear, df)
papsmearpast1y_ls9dhs <- df_age_fig(age.groups, ls9dhs, papsmearpast1y, df)
papsmearpast3y_ls9dhs <- df_age_fig(age.groups, ls9dhs, papsmearpast3y, df)
everhadpapsmear_ls14dhs <- df_age_fig(age.groups, ls14dhs, everhadpapsmear, df)
papsmearpast1y_ls14dhs <- df_age_fig(age.groups, ls14dhs, papsmearpast1y, df)
papsmearpast3y_ls14dhs <- df_age_fig(age.groups, ls14dhs, papsmearpast3y, df)

everhadpapsmear_ls9dhs$time_length <- "ever"
papsmearpast1y_ls9dhs$time_length <- "1y"
papsmearpast3y_ls9dhs$time_length <- "3y"
everhadpapsmear_ls14dhs$time_length <- "ever"
papsmearpast1y_ls14dhs$time_length <- "1y"
papsmearpast3y_ls14dhs$time_length <- "3y"

ls9_papsmear <- rbind(everhadpapsmear_ls9dhs[,c("agegr", "Mean", "time_length")],
                      papsmearpast1y_ls9dhs[,c("agegr", "Mean", "time_length")],
                      papsmearpast3y_ls9dhs[,c("agegr", "Mean", "time_length")])
ls9_papsmear <- pivot_wider(ls9_papsmear, names_from = "time_length", values_from = "Mean")
ls14_papsmear <- rbind(everhadpapsmear_ls14dhs[,c("agegr", "Mean", "time_length")],
                       papsmearpast1y_ls14dhs[,c("agegr", "Mean", "time_length")],
                       papsmearpast3y_ls14dhs[,c("agegr", "Mean", "time_length")])
ls14_papsmear <- pivot_wider(ls14_papsmear, names_from = "time_length", values_from = "Mean")

ls9_papsmear$Year <- 2009
ls9_papsmear$age2009 <- ls9_papsmear$agegr
ls9_papsmear$age2014 <- ls9_papsmear$agegr + 5
ls14_papsmear$Year <- 2014
ls14_papsmear$age2009 <- ls14_papsmear$agegr - 5
ls14_papsmear$age2014 <- ls14_papsmear$agegr 

lso_papsmear <- rbind(ls9_papsmear, ls14_papsmear)
View(round(lso_papsmear, 6))
```
```{r South Africa explore}
table(sabssm$ever_had_pap_smear)
table(sadhs$ever_had_pap_smear, sadhs$pap_smear_past_5y)

age.groups <- data.frame(15:49, 15:49)
df <- data.frame(agegr=15:49)
everhadpapsmear_sabssm <- df_age_fig(age.groups, sabssm, everhadpapsmear, df)
papsmearpast5y_sabssm <- df_age_fig(age.groups, sabssm, papsmearpast5y, df)
papsmearpast3y_sabssm <- df_age_fig(age.groups, sabssm, papsmearpast3y, df)
everhadpapsmear_sadhs <- df_age_fig(age.groups, sadhs, everhadpapsmear, df)
papsmearpast5y_sadhs <- df_age_fig(age.groups, sadhs, papsmearpast5y, df)
papsmearpast3y_sadhs <- df_age_fig(age.groups, sadhs, papsmearpast3y, df)

everhadpapsmear_sabssm$time_length <- "ever"
papsmearpast5y_sabssm$time_length <- "5y"
papsmearpast3y_sabssm$time_length <- "3y"
everhadpapsmear_sadhs$time_length <- "ever"
papsmearpast5y_sadhs$time_length <- "5y"
papsmearpast3y_sadhs$time_length <- "3y"

sa12_papsmear <- rbind(everhadpapsmear_sabssm[,c("agegr", "Mean", "time_length")],
                      papsmearpast5y_sabssm[,c("agegr", "Mean", "time_length")],
                      papsmearpast3y_sabssm[,c("agegr", "Mean", "time_length")])
sa12_papsmear <- pivot_wider(sa12_papsmear, names_from = "time_length", values_from = "Mean")
sa16_papsmear <- rbind(everhadpapsmear_sadhs[,c("agegr", "Mean", "time_length")],
                       papsmearpast5y_sadhs[,c("agegr", "Mean", "time_length")],
                       papsmearpast3y_sadhs[,c("agegr", "Mean", "time_length")])
sa16_papsmear <- pivot_wider(sa16_papsmear, names_from = "time_length", values_from = "Mean")

sa12_papsmear$Year <- 2012
sa12_papsmear$age2012 <- sa12_papsmear$agegr
sa12_papsmear$age2016 <- sa12_papsmear$agegr + 4
sa16_papsmear$Year <- 2016
sa16_papsmear$age2012 <- sa16_papsmear$agegr - 4
sa16_papsmear$age2016 <- sa16_papsmear$agegr 

zaf_papsmear <- rbind(sa12_papsmear, sa16_papsmear)
View(round(zaf_papsmear, 6))
```
```{r Zimbabwe explore}
table(zwdhs$ever_had_pap_smear)
table(zwphia$ever_had_pap_smear, zwphia$pap_smear_past_1y)

age.groups <- data.frame(15:49, 15:49)
df <- data.frame(agegr=15:49)
evercctested_zwdhs <- df_age_fig(age.groups, zwdhs, evercctested, df)
cctestpast1y_zwdhs <- df_age_fig(age.groups, zwdhs, cctestpast1y, df)
evercctested_zwphia <- df_age_fig(age.groups, zwphia, evercctested, df)
cctestpast1y_zwphia <- df_age_fig(age.groups, zwphia, cctestpast1y, df)

evercctested_zwdhs$time_length <- "ever"
cctestpast1y_zwdhs$time_length <- "1y"
evercctested_zwphia$time_length <- "ever"
cctestpast1y_zwphia$time_length <- "1y"

zw15_cctest <- rbind(evercctested_zwdhs[,c("agegr", "Mean", "time_length")],
                      cctestpast1y_zwdhs[,c("agegr", "Mean", "time_length")])
zw15_cctest <- pivot_wider(zw15_cctest, names_from = "time_length", values_from = "Mean")
zw16_cctest <- rbind(evercctested_zwphia[,c("agegr", "Mean", "time_length")],
                       cctestpast1y_zwphia[,c("agegr", "Mean", "time_length")])
zw16_cctest <- pivot_wider(zw16_cctest, names_from = "time_length", values_from = "Mean")

zw15_cctest$Year <- 2015
zw15_cctest$age2012 <- zw15_cctest$agegr
zw15_cctest$age2016 <- zw15_cctest$agegr + 1
zw16_cctest$Year <- 2016
zw16_cctest$age2012 <- zw16_cctest$agegr - 1
zw16_cctest$age2016 <- zw16_cctest$agegr 

zw15_cctest$ever_diff <- NA
for(a in 1:length(unique(zw15_cctest$agegr))){
  zw15_cctest$ever_diff[a+1] <- zw15_cctest$ever[zw15_cctest$agegr == (a+15)] - zw15_cctest$ever[zw15_cctest$agegr == (a+14)]
}
zw16_cctest$ever_diff <- NA
for(a in 1:length(unique(zw16_cctest$agegr))){
  zw16_cctest$ever_diff[a+1] <- zw16_cctest$ever[zw16_cctest$agegr == (a+15)] - zw16_cctest$ever[zw16_cctest$agegr == (a+14)]
}

zwe_cctest <- rbind(zw15_cctest, zw16_cctest)
View(round(zwe_cctest, 6))

mean(zw15_cctest$ever_diff, na.rm = T)
mean(zw15_cctest$"1y", na.rm = T)
```


