---
title: "Summary Statistics and Tables"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r tables}
#survey size characteristics
nrow(dat_anytest_3y)
nrow(dat_anytest_ever)
nrow(dat_anytest_all)
nrow(dat_anytest)
overall <- filter(dat_anytest, !is.na(any_test_past_3y) | !is.na(any_test_ever))
past_3y <- filter(dat_anytest, !is.na(any_test_past_3y))
ever <- filter(dat_anytest, !is.na(any_test_ever))

#obtain values from tabulations
bfsteps <- c(0.079, 0.056, 0.102) #estimate for ages 30-49 will assume its the same for all age groups between those ages
  
  p_bf <- bfsteps[1]
  lci_bf <- bfsteps[2]
  uci_bf <- bfsteps[2]
  
  bfsteps_den <- round(p_bf*(1-p_bf)/((p_bf - lci_bf)/1.96)^2)
  bfsteps_num <- round(bfsteps_den*p_bf)
  
  df_bfsteps <- data.frame(agegr = c("30-34", "35-39", "40-44", "45-49"),
                           prob = rep(bfsteps[1], 4),
                           den = round(rep(bfsteps_den/4, 4)),
                           num = round(rep(bfsteps_num/4, 4)))
  
  #add values from Mozambique STEPS tabulations
  mzsteps_3055 <- 0.035
  mzsteps_den <- rep(871/5, 5)
  
  df_mzsteps <- data.frame(agegr = c("30-34", "35-39", "40-44", "45-49"),
                           prob = rep(mzsteps_3055, 4),
                           den = round(c(rep(871/5, 4))),
                           num = round(c(rep(871/5*mzsteps_3055, 4))))
  
  #add values from zw20phia
  zw20phia <- c(0.27, 0.364, 0.325, 0.382, 0.429)
  zw20phia_den <- c(168, 257, 318, 307, 389)
  zw20phia_num <- zw20phia*zw20phia_den
  
  df_zw20phia <- data.frame(agegr = c("25-29", "30-34", "35-39", "40-44", "45-49"),
                           prob = zw20phia,
                           den = round(zw20phia_den),
                           num = round(zw20phia_num))
  
  #add extra columns to data frames to match dat_timetrends_gr
  df_bfsteps$df <- "bfsteps"
  df_bfsteps$time_length <- "ever"
  df_bfsteps$Country <- "Burkina Faso"
  df_bfsteps$hivstat <- NA
  
  df_mzsteps$df <- "mzsteps"
  df_mzsteps$time_length <- "ever"
  df_mzsteps$Country <- "Mozambique"
  df_mzsteps$hivstat <- NA
  
  df_zw20phia$df <- "zw20phia"
  df_zw20phia$time_length <- "ever"
  df_zw20phia$Country <- "Zimbabwe"
  df_zw20phia$hivstat <- 1

  df_to_add <- rbind(df_bfsteps, df_mzsteps, df_zw20phia)
  df_to_add <- select(df_to_add, -prob)
  
overall_resp <- nrow(overall) + sum(df_to_add$den)
length(unique(a$df));length(unique(a$Country)) + 1

#look at by hiv status
#b <- filter(a, !is.na(hivstat));length(unique(b$df));length(unique(b$Country));nrow(b)

unique_df_overall <- rbind(unique(overall[,c("Country", "df")]), unique(df_to_add[,c("Country", "df")]))
count_1_overall <- rownames(filter(data.frame(num = table(unique_df_overall$Country) == 1), num == T)) 
count_2_overall <- rownames(filter(data.frame(num = table(unique_df_overall$Country) == 2), num == T)) 
count_3_overall <- rownames(filter(data.frame(num = table(unique_df_overall$Country) >= 3), num == T)) 

unique_df_past_3y <- unique(past_3y[,c("Country", "df")])
count_1_past_3y <- rownames(filter(data.frame(num = table(unique_df_past_3y$Country) == 1), num == T)) 
count_2_past_3y <- rownames(filter(data.frame(num = table(unique_df_past_3y$Country) == 2), num == T)) 
count_3_past_3y <- rownames(filter(data.frame(num = table(unique_df_past_3y$Country) >= 3), num == T)) 

unique_df_ever <- rbind(unique(ever[,c("Country", "df")]), unique(df_to_add[,c("Country", "df")]))
count_1_ever <- rownames(filter(data.frame(num = table(unique_df_ever$Country) == 1), num == T)) 
count_2_ever <- rownames(filter(data.frame(num = table(unique_df_ever$Country) == 2), num == T)) 
count_3_ever <- rownames(filter(data.frame(num = table(unique_df_ever$Country) >= 3), num == T)) 

df_1_overall <- overall[overall$Country %in% count_1_overall,];length(unique(df_1_overall$df));length(unique(df_1_overall$Country));nrow(df_1_overall) 
df_2_overall <- overall[overall$Country %in% count_2_overall,];length(unique(df_2_overall$df));length(unique(df_2_overall$Country));nrow(df_2_overall) 
df_3_overall <- overall[overall$Country %in% count_3_overall,];length(unique(df_3_overall$df));length(unique(df_3_overall$Country));nrow(df_3_overall) 

df_1_past_3y <- past_3y[past_3y$Country %in% count_1_past_3y,];length(unique(df_1_past_3y$df));length(unique(df_1_past_3y$Country));nrow(df_1_past_3y) 
df_2_past_3y <- past_3y[past_3y$Country %in% count_2_past_3y,];length(unique(df_2_past_3y$df));length(unique(df_2_past_3y$Country));nrow(df_2_past_3y) 
df_3_past_3y <- past_3y[past_3y$Country %in% count_3_past_3y,];length(unique(df_3_past_3y$df));length(unique(df_3_past_3y$Country));nrow(df_3_past_3y) 

df_1_ever <- ever[ever$Country %in% count_1_ever,];length(unique(df_1_ever$df));length(unique(df_1_ever$Country));nrow(df_1_ever) 
df_2_ever <- ever[ever$Country %in% count_2_ever,];length(unique(df_2_ever$df));length(unique(df_2_ever$Country));nrow(df_2_ever) 
df_3_ever <- ever[ever$Country %in% count_3_ever,];length(unique(df_3_ever$df));length(unique(df_3_ever$Country));nrow(df_3_ever) 

cc_survey_char <- data.frame(Type = c("Only Past 3Y", "Only Ever", "Past 3Y and Ever", "Overall"),
                             N = c(30789, 73946 + bfsteps_den + snsteps_den, 147176, 251911 + bfsteps_den + snsteps_den),
                             Surveys = c(18, 15, 13, 46),
                             Countries = c(18, 12, 10, 25),
                             Years = c("2003", "2000-2019", "2009-2019", "2000-2019"))
cc_survey_char2 <- data.frame(Surveys_Per_Country = c(rep(1,3), rep(2,3), rep("3+",3), rep("Any", 3)),
                                           Type = rep(c("Past 3Y", "Ever", "Overall"), 4),
                                           N = c(nrow(df_1_past_3y), nrow(df_1_ever) + sum(df_mzsteps$den), nrow(df_1_overall) + sum(df_mzsteps$den), 
                                                 nrow(df_2_past_3y), nrow(df_2_ever) + sum(df_bfsteps$den), nrow(df_2_overall) + sum(df_bfsteps$den), 
                                                 nrow(df_3_past_3y), nrow(df_3_ever) + sum(df_zw20phia$den), nrow(df_3_overall) + sum(df_zw20phia$den), 
                                                 nrow(past_3y), nrow(ever) + sum(df_to_add$den), nrow(overall) + sum(df_to_add$den)), 
                                           Countries = c(length(count_1_past_3y), length(count_1_ever), length(count_1_overall),
                                                         length(count_2_past_3y), length(count_2_ever), length(count_2_overall), 
                                                         length(count_3_past_3y), length(count_3_ever), length(count_3_overall),
                                                         length(unique(past_3y$Country)), length(unique(ever$Country)) + 1, length(unique(overall$Country)) + 1),
                                           Surveys = c(length(unique(df_1_past_3y$df)), length(unique(df_1_ever$df)) + 1, length(unique(df_1_overall$df)) + 1, 
                                                       length(unique(df_2_past_3y$df)), length(unique(df_2_ever$df)) + 1, length(unique(df_2_overall$df)) + 1,
                                                       length(unique(df_3_past_3y$df)), length(unique(df_3_ever$df)) + 1, length(unique(df_3_overall$df)) + 1, 
                                                       length(unique(past_3y$df)), length(unique(ever$df)) + 3, length(unique(overall$df)) + 3),
                                           Years = c("2003-2018", "2011-2019", "2003-2019", 
                                                     "2003-2018", "2000-2018", "2000-2018",
                                                     "2003-2016", "2012-2020", "2000-2020",
                                                     "2003-2019", "2000-2020", "2000-2020"))
names(cc_survey_char2)[names(cc_survey_char2) == "Surveys_Per_Country"] <- "Surveys Per Country"
cc_survey_char2$Type <- factor(cc_survey_char2$Type, levels = c("Past 3Y", "Ever", "Overall"))
x <- with(cc_survey_char2, cc_survey_char2[order(cc_survey_char2$Type),])

cc_survey_char2_fr <- data.frame(Surveys_Per_Country = c(rep(1,3), rep(2,3), rep("3+",3), rep("Tout", 3)),
                                           Type = rep(c("3a", "À vie", "Tout"), 4),
                                           N = c(76613, 65981, 67788, 
                                                 55623, 129830 + bfsteps_den + snsteps_den, 38944 + bfsteps_den + snsteps_den, 
                                                 45729, 25311, 145179,
                                                 177965, 221122 + bfsteps_den + snsteps_den, 251911 + bfsteps_den + snsteps_den),
                                           Pays = c(17, 9, 12, 
                                                         4, 8, 6, 
                                                         2, 1, 7, 
                                                         23, 18, 25),
                                           Enquêtes = c(17, 9, 12, 
                                                             8, 16, 12, 
                                                             6, 3, 22, 
                                                             31, 25, 46),
                                           Années = c("2003-2018", "2011-2019", "2003-2019", 
                                                     "2003-2018", "2000-2018", "2000-2018",
                                                     "2003-2016", "2012-2015", "2000-2017",
                                                     "2003-2019", "2000-2019", "2000-2019"))
names(cc_survey_char2_fr)[names(cc_survey_char2_fr) == "Surveys_Per_Country"] <- "Enquêtes par Pays"
cc_survey_char2_fr$Type <- factor(cc_survey_char2_fr$Type, levels = c("3a", "À vie", "Tout"))
x_fr <- with(cc_survey_char2_fr, cc_survey_char2_fr[order(cc_survey_char2_fr$Type),])

kbl(cc_survey_char2, align = "c") %>%
  kable_classic()
kbl(x_fr, align = "c") %>%
  kable_classic()
ltc_survey_char <- data.frame(Type = c("Received result", "Had follow up appointment", "Treated", "Treated same day"),
                              N = c(6642, 618, 129, 96),
                              Surveys = c(6, 5, 3, 3))

kbl(ltc_survey_char, align = "c") %>%
  kable_classic()

a <- filter(dat_anytest, !is.na(any_test_past_3y) | !is.na(any_test_ever));length(unique(a$df));length(unique(a$Country));nrow(a)
b <- filter(a,!is.na(hivstat));length(unique(b$df));length(unique(b$Country));nrow(b)
unique_df <- unique(a[,c("Country", "df")])

cc_survey_char_hiv <- data.frame(HIV = c("Yes", "No"),
                                 Countries = c("12", "16"),
                                 Surveys = c("16", "36"))

names(cc_survey_char_hiv)[names(cc_survey_char_hiv) == "HIV"] <- "HIV Biomarker Data"
kbl(cc_survey_char_hiv, align = "c") %>%
  kable_classic()

cc_survey_char_hiv_fr <- data.frame(HIV = c("Oui", "Non"),
                                 Pays = c("12", "13"),
                                 Enquêtes = c("15", "31"))

names(cc_survey_char_hiv_fr)[names(cc_survey_char_hiv_fr) == "HIV"] <- "Données sur les biomarqueurs du VIH"
kbl(cc_survey_char_hiv_fr, align = "c") %>%
  kable_classic()

agegr1524 <- nrow(filter(a, age>=15 & age <=24))
agegr2549 <- nrow(filter(a, age>=25 & age <=49)) + sum(df_to_add$den)
agegr50 <- nrow(filter(a, age>=50 & age <=1000))
agegrall <- nrow(a) + sum(df_to_add$den)
cc_survey_age <- data.frame(Age.Group = c("15-24", "25-49", "50+", "Overall"),
           N = c(agegr1524, agegr2549, agegr50 , agegrall))
names(cc_survey_age)[names(cc_survey_age) == "Age.Group"] <- "Age Group"
kbl(cc_survey_age, align = "c") %>%
  kable_classic()

#determinants characteristics
det_char <- data.frame(Determinant = c("Urban/Rural", 
                                       "HIV Status", 
                                       "Health Insurance", 
                                       "Controlling Behaviours",
                                       "Education",
                                       "Wealth Quintile",
                                       "Sexual Activity Level",
                                       "Marital Status"),
                       N = c(177649, 115034, 49496, 12343, 174926, 132757, 63464, 177332),
                       Surveys = c(31, 12, 6, 3, 31, 12, 8, 31))
kbl(det_char, align = "c") %>%
  kable_classic()
```
```{r survey characteristics}
hiv_df_gr <- readRDS("hiv_dat_timetrends_gr.rds")

#countries with 2 or more surveys
table(unique(hiv_df_gr[,c("Country", "df")])$Country)
table((table(unique(hiv_df_gr[,c("Country", "df")])$Country) >= 2))

#countries with biomarker data
length(unique(hiv_df_gr[hiv_df_gr$'HIV Biomarker' == "Y", "Country"]))
length(unique(hiv_df_gr[hiv_df_gr$'HIV Biomarker' == "Y", "df"]))

#countries with each screening interval
a <- unique(hiv_df_gr[,c("df", "time_length")])
b <- data.frame(multi = table(a$df) >= 2, df = names(table(a$df)))

c <- left_join(a, b)

length(table(c[c$multi == T,]$df))
length(table(c[c$multi == F & c$time_length == "3y",]$df))
length(table(c[c$multi == F & c$time_length == "ever",]$df))

#number of female participants for each analysis
#screening
nrow(dat_anytest_3y) #load these dataframes from the group logistic regression.R code 
nrow(dat_anytest_ever)
nrow(dat_anytest_all)
nrow(dat_anytest)
overall <- filter(dat_anytest, !is.na(any_test_past_3y) | !is.na(any_test_ever))
past_3y <- filter(dat_anytest, !is.na(any_test_past_3y))
ever <- filter(dat_anytest, !is.na(any_test_ever))

#obtain values from tabulations
bfsteps <- c(0.079, 0.056, 0.102) #estimate for ages 30-49 will assume its the same for all age groups between those ages
  
  p_bf <- bfsteps[1]
  lci_bf <- bfsteps[2]
  uci_bf <- bfsteps[2]
  
  bfsteps_den <- round(p_bf*(1-p_bf)/((p_bf - lci_bf)/1.96)^2)
  bfsteps_num <- round(bfsteps_den*p_bf)
  
  df_bfsteps <- data.frame(agegr = c("30-34", "35-39", "40-44", "45-49"),
                           prob = rep(bfsteps[1], 4),
                           den = round(rep(bfsteps_den/4, 4)),
                           num = round(rep(bfsteps_num/4, 4)))
  
  #add values from Mozambique STEPS tabulations
  mzsteps_3055 <- 0.035
  mzsteps_den <- rep(871/5, 5)
  
  df_mzsteps <- data.frame(agegr = c("30-34", "35-39", "40-44", "45-49"),
                           prob = rep(mzsteps_3055, 4),
                           den = round(c(rep(871/5, 4))),
                           num = round(c(rep(871/5*mzsteps_3055, 4))))
  
  #add values from zw20phia
  zw20phia <- c(0.27, 0.364, 0.325, 0.382, 0.429)
  zw20phia_den <- c(168, 257, 318, 307, 389)
  zw20phia_num <- zw20phia*zw20phia_den
  
  df_zw20phia <- data.frame(agegr = c("25-29", "30-34", "35-39", "40-44", "45-49"),
                           prob = zw20phia,
                           den = round(zw20phia_den),
                           num = round(zw20phia_num))
  
  #add extra columns to data frames to match dat_timetrends_gr
  df_bfsteps$df <- "bfsteps"
  df_bfsteps$time_length <- "ever"
  df_bfsteps$Country <- "Burkina Faso"
  df_bfsteps$hivstat <- NA
  
  df_mzsteps$df <- "mzsteps"
  df_mzsteps$time_length <- "ever"
  df_mzsteps$Country <- "Mozambique"
  df_mzsteps$hivstat <- NA
  
  df_zw20phia$df <- "zw20phia"
  df_zw20phia$time_length <- "ever"
  df_zw20phia$Country <- "Zimbabwe"
  df_zw20phia$hivstat <- 1

  df_to_add <- rbind(df_bfsteps, df_mzsteps, df_zw20phia)
  df_to_add <- select(df_to_add, -prob)
  
overall_resp <- nrow(overall) + sum(df_to_add$den)
length(unique(a$df));length(unique(a$Country)) + 1

#isolate to only those 25-49
overall_2549 <- filter(overall, age >= 25 & age <= 49)

#number of women used for analysis with screening
nrow(overall_2549) + sum(df_to_add$den)

#treatment
overall_treatment <- filter(dat_anytest, !is.na(cc_treated))
nrow(overall_treatment)
table(overall_treatment$age)

#percent of the female population
countries <- unique(pooled_surveys$Country)

pop_age <- read_excel("pop_age2020.xlsx", sheet = 2) #i should change this so i can use the age structure for every year
  colnames(pop_age) <- pop_age[1,]
  pop_age <- pop_age[-c(1:4), -c(1, 3:5)]
  pop_age[,-1] <- lapply(pop_age[,-1], as.numeric)
  #isolate to only those of a certain age
  pop_age <- pop_age[,c("Location", agegr)] #rmbr to use the age groups that were used for the model even if the post-model analysis uses other age groups
  pop_age_long <- pivot_longer(pop_age, cols = -1, names_to = "agegr", values_to = "f_pop")
  pop_age_long$agegr <- as.numeric(factor(pop_age_long$agegr))
  names(pop_age_long)[names(pop_age_long) == "Location"] <- "Country"
  #clean up data to match 
  pop_age_long$Country[pop_age_long$Country == "Cabo Verde"] <- "Cape Verde"
  pop_age_long$Country[pop_age_long$Country == "Congo"] <- "Congo (Rep)"
  pop_age_long$Country[pop_age_long$Country == "Côte d'Ivoire"] <- "Cote d'Ivoire"
  pop_age_long$Country[pop_age_long$Country == "United Republic of Tanzania"] <- "Tanzania"
 
  View(pop_age)
  read_excel("pop_age2020_ssa.xlsx", sheet = 2)
  pop_age_ssa <- 42478 + 36391 + 30740 + 25006 + 20227
  pop_age_count <- sum(pop_age_long[pop_age_long$Country %in% countries,]$f_pop)
  
  pop_age_count/pop_age_ssa
  
  #sample size of women 25-49 for each age group
  agegr <- c("25-29", "30-34", "35-39", "40-44", "45-49")
  a <- hiv_df_gr[hiv_df_gr$agegr %in% agegr, ]
  
  b <- a %>%
    group_by(df) %>%
    summarise(df, Country, Region, Year, sum(denominator_original))
  
  View(unique(b))
```
